### ISSUE TITLE
@cardstack/hub installation issue

### ISSUE THREAD

**Issue by goo32** [cardstack/cardstack#10]
I was following along with Edward's EmberConf [talk ](https://www.youtube.com/watch?v=9DsBHKj90EY) and everything was going great until I tried to install 'hub'. (ember install @cardstack/hub). The install failed with the following error:
```
~>ember install @cardstack/hub
NPM: Installed @cardstack/hub
Unexpected identifier
C:\Users\me\Projects\anapp\node_modules\@cardstack\hub\index.js:15
  async serverMiddleware({ app, options }) {
        ^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
   ...
```
Btw, Edward uses `ember add @cardstack/hub` in the talk which is not an available command in my version of ember cli (2.12.2) so maybe this is the issue? Also, I'm on Win 7.

**Comment by sohara** [comment]
I believe you need to be using node 7.x due to some newer ES features like async/await.

**Comment by ef4** [comment]
@sohara is correct, the minimum node version we support is 7.x.

`ember add` was my mistake -- I was mixing up `ember install` and `yarn add`. The correct command is `ember install`.

**Comment by goo32** [comment]
That fixes this particular issue. Thank you.

I'm running into some other issues but I think it's my environment at this point... I'll attempt to work through it before making any more noise.
