### ISSUE TITLE
Bug - card builder elements have horizontal scrollbars

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1001]
These screenshots are from Chrome, at normal zoom, using a 13in Macbook. The same issue was present in Firefox. In the images below, you can see the scrollbars as well as some things that appear to be misaligned for the same % or pixels as the scrollbar accounts for.

<img width="1424" alt="Screen Shot 2019-11-15 at 11 47 38 AM" src="https://user-images.githubusercontent.com/16627268/68978895-0eb8c600-07ca-11ea-8254-bb65ca13a193.png">

<img width="1424" alt="Screen Shot 2019-11-15 at 11 39 33 AM" src="https://user-images.githubusercontent.com/16627268/68978901-14161080-07ca-11ea-960c-2a04418d3535.png">

**Comment by bagby** [comment]
@jenweber you don't happen to have this setting, do you?

<img width="668" alt="Screen Shot 2019-11-18 at 2 09 30 PM" src="https://user-images.githubusercontent.com/176297/69082009-3e0b4500-0a0d-11ea-9e3a-30fa9bda27ee.png">

**Comment by jenweber** [comment]
No, I have "Automatically based on mouse or trackpad" selected.

I think this must have to do with resolution. I just took a closer look at this issue and only see these scrollbars when I am not using my second monitor.

<img width="1310" alt="68077498-63f0e280-fd9b-11e9-9a32-bc5d2754e130" src="https://user-images.githubusercontent.com/16627268/69092180-d4ddfe80-0a19-11ea-9cd2-b7cb47ef8a3f.png">

**Comment by bagby** [comment]
I was unable to repro, when I changed "Show Scroll Bars" to "Always", it looked exactly like your original screenshot, regardless of resolution 😕

**Comment by burieberry** [comment]
Good to know how to reproduce this. now we can fix accordingly

**Comment by burieberry** [comment]
@jenweber how do the scrollbars look now after the recent changes?

**Comment by jenweber** [comment]
These look fixed now!

<img width="1319" alt="Screen Shot 2019-12-03 at 10 31 58 AM" src="https://user-images.githubusercontent.com/16627268/70064837-2eb4fb80-15b8-11ea-8fe3-1756fbd9f46b.png">
