### ISSUE TITLE
Move Login/logout buttons to the context menu displayed when user clicks profile icon

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1014]
When user is logged out profile icon should display cardstack logo. 
When user clicks on Cardstack logo, the left edge would open and context menu displayed in it. The context menu would have "Log In | Sign Up" items for social logins. The only active button would be "Log In with GitHub", all other are disabled and marked "Coming Soon" (see xd). 
When user is logged in profile icon should display user's profile picture. For GitHub login it would display user's GitHub avatar. When user clicks on it, left edge would open. Next to profile picture we would display user's name and GitHub username. When user clicks on them we would take user to profile page (#1200). 

XD: `login sequence.xd` https://drive.google.com/open?id=1RSxnpEKSHzm4SLQiYE2FbfS5zZ4fRK-T

**Comment by jenweber** [comment]
Todo:
- [ ] replace profile icon with cardstack logo
- [ ] apply a background to the left edge
- [ ] Click to toggle left edge width and reveal more buttons
- [ ] animate the left edge reveal
- [ ] remove login/logout buttons from all pages
- [ ] add buttons to the revealed panel
- [ ] Check to make sure nav works for keyboard commands
- [ ] make sure it still looks ok in smaller screens
- [ ] tests
