### ISSUE TITLE
Drop target behavior on drag and drop

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1017]
current state
![image](https://user-images.githubusercontent.com/1836666/71841768-2e63c080-308e-11ea-9086-3e8828645d3b.png)

- [ ] When dragging a UI component over drop target it should grow and push down existing components. Before being dropped the component being dragged should be displayed in that space with opacity 35% (currently it is displayed with 100% opacity - see the "current state" attached image)
![drag_and_drop_over_target](https://user-images.githubusercontent.com/1836666/69091138-ad863200-0a17-11ea-9afd-6ce60e118509.png)
- [ ] The sensitive area in which drag and drop target activates is currently limited to the thin line between fields, it should be larger: 
![image](https://user-images.githubusercontent.com/1836666/71843397-c911ce80-3091-11ea-9f46-c1db2be8684d.png)
- [ ] During dragging the component in motion should have rounded corners - currently, they are straight

**Comment by bagby** [comment]
"During dragging the component in motion should have rounded corners - currently, they are straight" we're using HTML5 native drag & drop, that's not really a thing we have control over. Technically speaking they *do* have rounded corners, but the background color of the left edge is also being rendered in the dragged object. If we want to be able to have complete control over the styling of the dragged object, we'll need to use `ember-animated` or something other than native drag & drop.
@dnaidionov

**Comment by dnaidionov** [comment]
> * During dragging the component in motion should have rounded corners - currently, they are straight

@bagby ok, this is minor issue/non-issue, so good for now. we'll return to this if needed
