### ISSUE TITLE
Button state management and messaging during save operation. 

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1021]
We should make a dedicated save button component.

0. Initially, when there are no changes, "Save" button label signals user that everything is changed, and the button itself is disabled, and its opacity is set to 50%
![image](https://user-images.githubusercontent.com/1836666/69258766-22c64400-0b8b-11ea-9f0b-4d776e18b14b.png)

1. During regular work save button is displayed in normal state and label signals available action - "Save"
![image](https://user-images.githubusercontent.com/1836666/69165949-6b64fb00-0ac0-11ea-89ed-1b3c598988a1.png)

2. When a user clicks it, while the save operation is going on, the button changes to include saving indicator (spinning wheel - use second CSS animation from this page: https://projects.lukehaas.me/css-loaders/) and button label is changing to "Saving"
![image](https://user-images.githubusercontent.com/1836666/69166034-951e2200-0ac0-11ea-9508-7c7105408dc0.png)

3. When save is successful button label and background change to indicate that
![image](https://user-images.githubusercontent.com/1836666/69166302-02ca4e00-0ac1-11ea-8f61-5831d945fd3e.png)

4. After 5 seconds button returns to initial state
![image](https://user-images.githubusercontent.com/1836666/69258766-22c64400-0b8b-11ea-9f0b-4d776e18b14b.png)

5. In case of error, the button is changing to indicate that, and modal with error message pops up (when the modal is displayed the card is dimmed - see general rules for displaying modals - "System/Error Messaging" section of the XD). Modal has to be dismissed by the user. "Save" button changes to state 1 (card is dirty and there are unsaved changes) 3 seconds after modal is dismissed. 
![image](https://user-images.githubusercontent.com/1836666/69253963-79c81b00-0b83-11ea-8dbc-7ad9724a17ac.png)

Transitions between button states should be fading. 

When testing, make sure that the dirty state also reflects when changes are made to CSS themes.

XD file: https://drive.google.com/open?id=1xSnis7586pGMysyWycrjvGHM7GQzbLZm. See artboards sequence in the section "Save Indicator" 
![image](https://user-images.githubusercontent.com/1836666/69167234-9d775c80-0ac2-11ea-8384-f1c47d3804b8.png)

**Comment by habdelra** [comment]
@dnaidionov for number 4, in the case where the save has just completed, and there are no unsaved changes--does it really make sense to show a save button if there is nothing to save? our data service is smart enough to tell us if there are no unsaved changes (there is a `card.isDirty` property).

**Comment by dnaidionov** [comment]
We can make button disabled and enable it only when there are changes. If `card.isDirty` is false the button label could also say "no changes" or smth similar so users don't have to guess why there's no save
