### ISSUE TITLE
Add percy tests to card builder

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1030]
PR number one will cover the easy things.

PR number two will account for animations.

**Comment by jenweber** [comment]
> Module not found: Error: Can't resolve '../../../node_modules/ember-percy/finalize' in '/private/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/embroider/dc7224/packages/cardhost/assets/@cardstack'

`../../../node_modules/ember-percy` is an incorrect relative path. This seems to be a problem with the mono-repo and not embroider. I was not able to reproduce in a non-mono-repo setting.

**Comment by ef4** [comment]
Embroider fix for this: https://github.com/embroider-build/embroider/pull/360
