### ISSUE TITLE
New card's route should change after saving

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1036]
When we save a new card we are still in the /cards/new route even after the card has an official ID. This is really problematic, as that route does not represent the current state of the application nor the current state of the card.

From @habdelra: 

> something like: 
> `this.router.transitionTo('cards.schema', this.card.name);`

Also, we should add a test for this scenario too so that `currentURL()` actually reflects the newly saved card's ID

**Comment by robustdj** [comment]
This might only be happening when there's an error while saving. A successful save, redirects to the `card.view` route.

**Comment by robustdj** [comment]
And then when an error occurs, it stays on the `/cards/new` route and keeps the loading indicator in place

![Screen_Shot_2019-11-19_at_8 09 39_PM](https://user-images.githubusercontent.com/118005/69252541-049b1c80-0b68-11ea-92ea-c5098c14b22d.png)

**Comment by bagby** [comment]
Closed by #1053
