### ISSUE TITLE
Update CTA ui-component

### ISSUE THREAD

**Issue by burieberry** [cardstack/cardstack#1039]
Part of #1046 

<img width="365" alt="buttons" src="https://user-images.githubusercontent.com/16160806/69254102-b09e3100-0b83-11ea-80fa-fb2747182c82.png">

<img width="307" alt="icon-buttons" src="https://user-images.githubusercontent.com/16160806/69254112-b267f480-0b83-11ea-89a6-6bb34dc6ed6f.png">

**Comment by jenweber** [comment]
@burieberry do you know which tasks on this ticket still remain?
