### ISSUE TITLE
Create an image core type

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1064]
Similar to how we have fields for Text, Date, Number, we should create a core type for image. This can be an "old style" core type, similar to text and date, for this first pass. In the future, our core types will be cards but this is out of scope.

The image core type/card can be as lightweight as:

```handlebars
<div class="some-class {{additionalClasses}}">
  <img src={{someUrl}} alt={{altText}} />
  <div>{{caption}}</div>
</div>
```

The user will provide the image via their own URL (i.e. something on imgur)

In cases of decorative images, `alt=""` is what should be used, so we should make sure that property and value show up as a default, when no value is provided. [more info](https://www.w3.org/WAI/tutorials/images/) and [this](https://www.w3.org/WAI/tutorials/images/decision-tree/)

Helper test (if we are using it) can give the user a clue about how to fill in alt.

**Comment by jenweber** [comment]
@dnaidionov please feel free to edit my description above

**Comment by habdelra** [comment]
I don’t think this would actually be a core type. Core types are reserved for scalar values. Rather this would be a type of card.

**Comment by habdelra** [comment]
And in order to have an “image card” that means we need to support cards with custom template. (So run-time embroider compiled card templates)

**Comment by habdelra** [comment]
You could also argue that an “image card” is actually a card with a binary payload (or internal model) similar to what we did in cardboard. What you describe here might be more akin to a url or link card that is cognizant of how to handle different mike types.

**Comment by jenweber** [comment]
For this issue, I think what we should do first is to make an old-style core type. Then when we have the cards-as-fields feature available, we convert it to a card. It definitely should be a card eventually.

**Comment by jenweber** [comment]
Although, in order to support alt text, I suppose a core-type may not be able to help us here.

We could make this one be a "decorative" image type at first, where alt text is supposed to be `alt=""`, and it does not have a caption.

**Comment by habdelra** [comment]
This directly collides with the new hub work. I think we should be careful to say we rely on and old hub feature to implement this issue.

**Comment by habdelra** [comment]
I would suggest rephrasing this issue to be more like: "we need an image field" and let the implementation fall out from that instead of saying "core field" as that has a very specific meaning that is nearing obsolescence.

**Comment by jenweber** [comment]
For the initial demo in early January, we want to be able to show images, so we should still add an image core type, but per Hassan's comments, this work must rely on solely existing old hub features. This will also let us work out how we do want to do markup and themability of images, without creating work to undo later.

To-do:
- [ ] create `decorative-image-viewer.hbs` which is an image tag
- [ ] create `decorative-image-editor.hbs` which is just the existing textfield editor
- [ ] create `decorative-image.js` which validates the entry is a string
- [ ] add core-types data to `mappings.js`
- [ ] add the new core type to the embroider config for cardhost in `ember-cli-build.js` so that it gets included in builds
- [ ] style the image (just doing a hero image for now)
- [ ] tests!
