### ISSUE TITLE
Rules for Right Edge's card properties' sections availability in different modes

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1077]
When displaying card properties in the right edge some sections do not have actionable items/editable properties or are not accessible in the selected view. If that is the case, the section is displayed collapsed, the section name is dimmed, and instead of "unfold" icon it would display an icon of the mode where this section becomes available. When a user clicks on that icon, the card is switched to the relevant view.

![image](https://user-images.githubusercontent.com/1836666/69741056-67605b00-1108-11ea-9176-42e567b59d21.png)

Following is the availability of card properties' sections:

Card Name: Schema
Template: Schema, Edit, Layout
Appearance: Layout
Metadata: Schema, Edit, Layout

Appearance section displayed in views other than Layout: 
![image](https://user-images.githubusercontent.com/1836666/69741159-8e1e9180-1108-11ea-925e-079c5671fe6b.png)
Clicking on "Layout view" switched card to Layout view and opens Appearance section: 
![image](https://user-images.githubusercontent.com/1836666/69741281-c45c1100-1108-11ea-85be-ff57840ae5b0.png)

Card Name section in views other than Schema: 
![image](https://user-images.githubusercontent.com/1836666/69741325-db9afe80-1108-11ea-88cb-8022d9a50c21.png)

**Comment by burieberry** [comment]
This is on hold until we have more designs for the Metadata section. Putting it back into the queue
