### ISSUE TITLE
In Layout view when scrolling the card and card is reaches the header, display a shadow under the header.

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1078]
That would visually raise the header above the card content plane. When card is scrolled to the top, there should be no shadow

Card is at the top - no shadow:
![image](https://user-images.githubusercontent.com/1836666/69741703-84495e00-1109-11ea-919b-b67017543b84.png)

Card is scrolled - header throws a shadow: 
![image](https://user-images.githubusercontent.com/1836666/69741746-97f4c480-1109-11ea-853e-05177746afa4.png)

**Comment by jenweber** [comment]
As discussed in today's meeting, the shadow needs to go on the right edge and left edge of the schema view, not directly on the card itself.
