### ISSUE TITLE
Appearance section of card properties

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1079]
This issue has a WIP PR #1135 which someone needs to finish up.

In the Appearance section user is able to pick a predefined style. Each card can have at most three kinds of styles: 

- A card can use the default style provided by Cardstack. 
- If a card is based on a template it can use the style of the adopted template
- User can provide a custom style for the card by editing it in the built-in theme editor (#998)

By default when adopting a template card will use that template's style, and at that moment there would be no custom style. In that case, there would be a CTA to create a new custom style. It will open the theme editor with blank CSS.

If a custom theme for the card exists, the "create new" CTA is disabled, and when the user selects the custom theme, there's an option to remove it. 

When a custom theme or adopted card's theme is selected, the code snippet of the selected style is shown in the input field under the selection. When the user hovers over that input field, the CTA to edit the style slides in if the current style can be edited. Style can be edited if: 
- It is the custom style OR
- It is an adopted style and no custom style exists

If an adopted style is selected and a user clicks CTA to edit it, the following things happen: 
1. A new custom style is created
2. Style from adopted card is copied into it
3. Theme editor is opened with a newly created custom style
4. Custom style becomes currently selected in appearance section. 

XD: https://drive.google.com/open?id=1xSnis7586pGMysyWycrjvGHM7GQzbLZm
Artboard: "Template Adoption & Appearance Selection"

**Comment by jenweber** [comment]
Postponing until we have better handling of adoption
