### ISSUE TITLE
Theme editor view styling

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1082]
Theme editor (#998) is a separate view from other modes (Layout/Edit/Scheme). When the card's  Theme editor is opened it takes over the entire viewport. Edges are hidden, instead, the editor displays its own controls. 
The card itself is displayed in the layout preview mode. All interactions within the card are disabled (e.g. actions, content editing, etc), except those that modify visual styles - e.g. hover. 
Card's background in the theme editor is different from its background in other views - this signals that the main editing area is shifting from the card itself to the CSS editor, and rendered card now serves just as a preview.

The top bar contains editor and preview options: 
- on the left side, we display card size and mode options
- on the right - the editor docking options, show/hide editor (when applicable - this control is not always visible), and Done editing CTA. 

By default card is displayed in responsive mode, CSS editor is docked on the right

![image](https://user-images.githubusercontent.com/1836666/69757284-a4d5e000-112a-11ea-82a9-b9b9d8df8bbf.png)

XD: https://drive.google.com/open?id=1xSnis7586pGMysyWycrjvGHM7GQzbLZm
Artboard: "Motion - CSS Editor"

**Comment by jenweber** [comment]
Closed by #1142
