### ISSUE TITLE
CSS/HTML editor resizing/collapsing

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1084]
- The entire editor panel has a gripper that is highlighted on hover. The width (when docked on the right) or height (when docked on the bottom) can be changed by dragging it. Editor size is limited to 80% max and 10% min. Editor panel cannot be resized more or less than that. 
- There is another gripper between CSS and HTML editor windows. Together CSS and HTML always take 100% of the height when docked on the dright, and 100% of the width when docked on the bottom. Users can scroll within code windows, but their combined size is fixed within the viewport. Users can change the relative size of the code windows by dragging the mentioned gripper.
- When dragging the gripper between code windows, they can be resized only to a certain minimum size (e.g. 3 lines of code visible when docked on the right, and 10% when docked on the bottom). If a user wants to completely collapse the code editor, they should use collapse/unfold icons in the editor header
- When users collapse one the code windows, another opens to fill the entire available area (even if it was collapsed before). 
- When user unfolds collapsed code window, windows' relative sizes are restored to the original configuration

Motion study video (resizing starts at 00:00:30): https://drive.google.com/file/d/1lkg7qA21ERS39DrPGrwmqxPwhtR5LrmT/view

Related cards:  #1082, #998

**Comment by jenweber** [comment]
Closed by  #1142 

Not all points are addressed 100%, but per the conversation today, I think what has just been merged matches the functional requirements.

max width is the screen width, by default. The same goes for height.

Individual code blocks are not resizable, but the larger panel is.
