### ISSUE TITLE
Bug: Card builder should have lightweight validations for field and card id

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1109]
To fix:
- [ ] Spaces in field names break cards permanently. Disallow spaces. This also impacts CSS styles.
- [ ] when you backspace to clear the field label, it autofills too eagerly with the id

Note that if you use ui-components, it has validation hooks built-in.

**Comment by jenweber** [comment]
Card name is now separate from id, so you can use all kinds of characters. Lightweight FE validation is in #1136.

@habdelra do we have any server side validation for field ids in new-hub?

**Comment by habdelra** [comment]
we have some real light validation, like the field cannot start with `cs`, and we also have the idea where the resulting field card needs to be valid JSONAPI (so i think that will catch special chars).

**Comment by jenweber** [comment]
Ok, I think in that case, we should go ahead and close this, and come back to it if we need more powerful measures.
