### ISSUE TITLE
Check cross-browser compatibility for Card Builder

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1111]
Try basic user flow in:
- Safari
- Edge

Assume coverage in Firefox & Chrome since the dev team uses them daily.

Use the free BrowserStack VM to test in Edge if you don't have Windows.

To close this ticket, comment with the results and open a new ticket describing bugs you find, one for each browser.

**Comment by dnaidionov** [comment]
See initial results here: #1121 
I used Experitest because they have a free plan vs limited trial on browserstack (i already used more than entire browserstack time limit). But in case it's an issue with Experitest VM, I will repeat on another provider

**Comment by jenweber** [comment]
I confirmed on a Windows VM that edge doesn't work there either, so it's not a remote VM problem.

Closed, will track to-dos in #1121
