### ISSUE TITLE
Make builder app compatable with Edge / IE11

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1121]
I'm using experitest (seetest.io) for cross-browser testing. To establish baseline I have confirmed that chrome emulation on OSX works as expected (smoke test). 

Chrome 78 on OSX High Sierra (whatever is available) - smoke test OK

Chrome 78 on Win 10 - smoke test OK

IE11 on Win 10 using experitest (seetest.io) - doesn't load at all. No Console errors. Here's a snapshot of the code loaded: 
![screenshot](https://user-images.githubusercontent.com/1836666/70561774-12393600-1b59-11ea-9d65-f7ebf1566fd0.png)

For the reference, same URL open in chrome generates `cardhost-welcome-page` div element that contains the page contents: 
![image](https://user-images.githubusercontent.com/1836666/70563788-e029d300-1b5c-11ea-84f7-68d6a2b38a8d.png)

Edge 17134 on Win 10 using experitest (seetest.io) - same as IE11. 4 console errors.
![screenshot (1)](https://user-images.githubusercontent.com/1836666/70562002-8ecc1480-1b59-11ea-87b1-95cec2c69b8d.png)
![screenshot (2)](https://user-images.githubusercontent.com/1836666/70562080-b58a4b00-1b59-11ea-99c6-84415ec4cdfa.png)

FF71 on Win 10 - smoke test OK

FF71 on OSX High Sierra - smoke test OK

Safari 13 on OSX High Sierra - smoke test OK

**Comment by jenweber** [comment]
Other possible to-dos:
- add an autoprefixer for css compatibility, i.e. https://github.com/jeffjewiss/ember-cli-postcss
- Firefox drag & drop is broken
- Schema page in Firefox is broken
