### ISSUE TITLE
On the launcher screen label is still moving on card hover

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1146]
Tha label resizing was fixed in #1104, but it is still slightly moving - as if several conflicting animations are taking place at the same time - see attached video. 

https://www.loom.com/share/a01c11452669416aa438d54f2a16c3c4

**Comment by jenweber** [comment]
The issue was that a scale-down was being applied to the container, at the same time that a scale-up was applied to the label. The fix is described in #1185
