### ISSUE TITLE
When opening an existing card in Schema view, the entire card and the last field are selected simultaneously

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1151]
When opening a card, only the card itself should be selected. Fields shouldn't be selected unless selected explicitly. 

Current state: 
![image](https://user-images.githubusercontent.com/1836666/71125405-d8011180-21b4-11ea-8914-e53bafc615d9.png)

This might be related to #1150

**Comment by bagby** [comment]
@dnaidionov I believe this was fixed a couple of weeks ago, can you check again?

**Comment by dnaidionov** [comment]
indeed. closing
