### ISSUE TITLE
Display confirmation prompt when a user tries to leave the dirty page.

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1155]
If a user has some unsaved changes and tries to switch to a different view  (layout/edit/schema), we should display a warning modal with options to proceed and return to the current page. 
Proceeding with route change will abandon changes. Returning to current card will allow the user to save them before navigating away.

Modal design - see  #1043
Icon: Warning
Title: "Unsaved changes"
Text: "You have some unsaved changes in this card. If you proceed to change the view or navigate away, they will be lost. If you want to save changes, please stay in this view and save them. Do you want to proceed, or stay?"
Buttons: "Proceed", "Stay"

**Comment by alexspeller** [comment]
Closing as this is no longer relevant with autosave
