### ISSUE TITLE
Rename text field cards in quick catalog

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1162]
Case insensitive text will be used more often than case sensitive, so we should make "Text" reference to case-insensitive, and specify case-sensitive text control - the opposite of what we have now. 
This is the current state 
![image](https://user-images.githubusercontent.com/1836666/71279626-377f2e80-2327-11ea-92e8-341f4a91a2b4.png)
 

Rename fields for core types in the card builder: 
- Text: 
  - name: "Text (case-sensitive)"
  - description: "Case-sensitive text field"
  - position: 2
- Text (case-insensitive)
  - name: "Text"
  - description: "All-purpose text field"
  - position: 1

**Comment by jenweber** [comment]
This ticket needs to incorporate Katrin's feedback before we implement.
