### ISSUE TITLE
Testing - fix Percy snapshot instability for animated components

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1182]
Whenever we run Percy snapshots that show the right edge, we need to await the fade animations before taking the snapshot.

I think we can use these test support utilities from the ember-animated library: https://github.com/ember-animation/ember-animated/tree/master/addon-test-support

However, they aren't documented. @ef4 do you consider these to be public API?

**Comment by ef4** [comment]
Yes, everything that you'd import directly out of `ember-animated/test-support` is public API.

**Comment by jenweber** [comment]
This is mostly fixed.
