### ISSUE TITLE
Edges should slide in/out when summoned/dismissed

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1209]
When edges are summoned or dismissed they should not just appear on screen, but slide in/out like in the following animation: 
https://www.loom.com/share/2f7e4496c76c40ac950896e994784a20
The transition speed should be synced with the other animation happening on screen. 

Currently, they are just appearing on screen on top of other animation that is happening:
https://www.loom.com/share/90bd9ab35aef4911bd9197a84e83782c

**Comment by alexspeller** [comment]
I believe this is blocked by #1249 - or at least, #1249 mentions that animations are currently blocked

**Comment by burieberry** [comment]
A little caviat, this _might_ become throwaway work _if_ we end up using the cardstack-edges package (exploratory work for that in #1236). Since then the sliding in and out comes built-in. But #1236 requires a ton of changes so I'm not sure when or if it would be ready to be merged.

**Comment by dnaidionov** [comment]
we need this transition to be able to judge if this is the right way to handle edges during route transitions. so even if we later switch to 1236, i'd rather have this sooner so that we have a working transition meanwhile
