### ISSUE TITLE
Don't generate field name from # of existing fields

### ISSUE THREAD

**Issue by bagby** [cardstack/cardstack#1212]
When adding a field to a card in Card Builder, it autogenerates the field name based on how many fields the card has, i.e. `field-{n-1}`. The problem with this approach is that, if you remove one or more fields, and then add another field, it is likely a field with that name already exists, and an exception is thrown. 

To recreate this:

 - go to https://builder.stack.cards/cards/new
 - add two fields
 - remove the first field
 - add another field

We should probably use a `nonce` that is auto-incremented when adding a field, or similar mechanic.

**Comment by jenweber** [comment]
Will & I decided to get the maximum of the field name numbers in use, and add 1. The rationale is that `field-522678982` loses the meaning and conciseness that `field-9` has.
