### ISSUE TITLE
Improve error message for issues connecting to the database

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1224]
If you forget to `yarn start-prereqs` to run cardhost, you get the following and then many spinoff errors:

```
  cardstack/server Starting main hub server
  cardstack/server Server failed to start cleanly: Error: connect ECONNREFUSED 127.0.0.1:5432
  cardstack/server     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
```

I think if the connection is refused, we should print a message "did you forget to start the local database?" or similar. Alternately, we could provide a command that spins up the database if it's not already running.

**Comment by habdelra** [comment]
i think spinning up the DB if it is not already running makes a lot of assumptions about the deployment environment which may not be true. But it should be easy to detect a ECONNREFUSED when starting the DB and providing a more helpful message about starting a DB.
