### ISSUE TITLE
Bug - Cannot save card 409 Conflict on a patch request

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1226]
In a testing environment, saving some CSS after edits causes a 409 conflict. This is not blocking, because if I use the existing "save" button, things are ok, but it is suspicious and it makes me wonder if a race condition has been introduced. @habdelra does this sound familiar to you? We have spent some time debugging and will mark it was `wontfix` and move on, unless you have a concern or clue here.

```text
Error: Cannot save card 409: Conflict
                at save (webpack:///../core/services/data.js?:1408:11)
                at async Card.save (webpack:///../core/services/data.js?:484:35)
                at async ThemerCardController.saveAndClose (webpack:///./controllers/cards/card/themer.js?:31:5)
```

## How to reproduce

This same test passes prior to merging in other people's work, if you check out `af15693d05bee55a3336f9bc7e0ee7657addc31a`
You can see the issue by checking out `e1ed972cf90b09b6ad4e6b63379796bb3d20590c` and running `ember test --filter "css editing"`.  The branch to look at is `debug-patch-409`

**Comment by habdelra** [comment]
yeah, this sounds like a leaky test. you'll see 409's anytime you don't cleanup properly as part of your test. (it could be that this test is leaking, or some other test is leaking into this test). In order to fix this, you'll need to find the test that is leaking cards and make sure to use the `destroy()` hook in the fixtures to cleanup the cards that leaked.

**Comment by habdelra** [comment]
you'll definitely want to track this issue down and fix it--as it might start to pollute other tests...

**Comment by jenweber** [comment]
I think we finally fixed this in the end by a) not saving the base card to git, b) not running seeds in production, and c) squashing existing git history
