### ISSUE TITLE
Bug - scrolling header is not handled on the themer route

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1230]
If you scroll down in the themer, this happens.

<img width="1436" alt="Screen Shot 2020-01-15 at 1 35 28 PM" src="https://user-images.githubusercontent.com/16627268/72460997-fd754100-379b-11ea-9107-1ab578c5675f.png">

@burieberry @bagby do you know if this is a quick fix?

**Comment by burieberry** [comment]
Seems like one of the containers needs `overflow: hidden`. I feel like there was a reason for not having that property here, but I don't remember what that was.

**Comment by jenweber** [comment]
This is fixed
