### ISSUE TITLE
Cannot add fields to the card after deleting a field

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1232]
When creating a card, or modifying a card's schema, if user deletes a field with autogenerated name (e.g. `field-3`), and that autogenerated name is not the largest autogenerated number (e.g. there exist a field with name `field-4` or `field-5` or higher), then user is getting an error trying to add another field  to the card. The error says 
```
'addField() called for card id 'local-hub::location-card-template' to add a new field 'fields/field-3' which already exists for this card.
```
The error is not happening if user deletes a field with the largest autogenerated name on current card.

**Comment by bagby** [comment]
@dnaidionov duplicate of #1212
