### ISSUE TITLE
Edit Mode Layout screen

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1248]
## Top edge:
See #1302 

## Right edge: 
- [x] The right edge should display a CTA to switch to "**Themer mode**" (e.g. "New Custom Theme" button, or "Edit Theme" button)

## Card header: 
- [x] See #1287 

## Background
The screen background is the color from our palette closest to #B7B1BA. 
![image](https://user-images.githubusercontent.com/1836666/72645727-4d8e0800-3942-11ea-93e7-30e3a4b791f5.png)
 The top edge should have a transparent background. 

## Transitions: 
- [ ] See #1289

**Comment by burieberry** [comment]
These items are complete, except the on-hold transitions. The background color in XD for edit layout mode is #2E2D38, which is already done, too.
