### ISSUE TITLE
Themer mode screen

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1261]
## Top edge:
See #1306

## Right edge: 
Right Edge is hidden

## Code Editor
The code editor occupies the right half of the screen. 

## Card header: 
The card header is not shown. Only the contents of the card as seen by the user in **view mode** are displayed. 

## Background
The background on which the card is displayed is the color from our palette closest to #5D5C6F. 
The background of the code editor side is the color from our palette closest to #000000 with 77% opacity. 

![image](https://user-images.githubusercontent.com/1836666/72837243-298d3800-3c5c-11ea-93e5-9964eb04afd1.png)

The top edge should have a transparent background. 

## Transitions: 
- For transitions when switching between this and Edit Layout screens see #1316 
- For transitions when switching between this and Preview screens see Preview screen ticket (#1262)

**Comment by jenweber** [comment]
- [x] Right Edge is hidden - handled in a previous PR
- [x] The code editor occupies the right half of the screen. - handled in a previous PR
- [x] The card header is not shown. Only the contents of the card as seen by the user in view mode are displayed. - handled in a previous PR
- [x] The background on which the card is displayed is the color from our palette closest to #5D5C6F. - The closes color is `#5A586A` aka `--ch-foreground`
- [x] The background of the code editor side is the color from our palette closest to #000000 with 77% opacity. Closest is `#000` aka `--ch-dark`. 77% opacity is too light to reliably read white text (see screenshot). Substituting 90%
- [x] The top edge should have a transparent background.

Screenshot showing that 77% is too light:
<img width="1252" alt="Screen Shot 2020-03-02 at 4 20 53 PM" src="https://user-images.githubusercontent.com/16627268/75718956-de763400-5ca1-11ea-8fd4-ad423385a83a.png">

90% opacity

<img width="1248" alt="Screen Shot 2020-03-02 at 4 22 17 PM" src="https://user-images.githubusercontent.com/16627268/75719025-02d21080-5ca2-11ea-8b03-d7adc7aaa6e5.png">

**Comment by jenweber** [comment]
The S M L buttons at the top have insufficient color contrast:

<img width="763" alt="Screen Shot 2020-03-02 at 4 43 14 PM" src="https://user-images.githubusercontent.com/16627268/75720769-159a1480-5ca5-11ea-833e-efd5b39d64fd.png">

Pure white is ok

<img width="739" alt="Screen Shot 2020-03-02 at 4 45 04 PM" src="https://user-images.githubusercontent.com/16627268/75720824-319db600-5ca5-11ea-9ad7-6b298c836358.png">
