### ISSUE TITLE
In View mode card header should be displayed on hover

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1266]
Right now user needs to click on the card to display the header - this is not obvious and leaves users wondering about what they need to do next.
![Kapture 2020-01-21 at 16 21 00](https://user-images.githubusercontent.com/1836666/72844330-4597d600-3c6a-11ea-8340-d8b9ce3d6c07.gif)

**Comment by alexspeller** [comment]
@bagby mentioned he thinks he has already completed this in an outstanding PR

**Comment by bagby** [comment]
@alexspeller correct, it is part of #1249
