### ISSUE TITLE
The Edit button in the card header should be styled as button

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1267]
Right now it is styled as text, it should look like button. 

Currently: 
![image](https://user-images.githubusercontent.com/1836666/72845112-e8048900-3c6b-11ea-81e7-5d6778db0bce.png)
 
Desired (keep colors consistent with current design, this is just for the general feel reference): 
![image](https://user-images.githubusercontent.com/1836666/72845149-ffdc0d00-3c6b-11ea-8a98-94c645cc1bc3.png)

**Comment by alexspeller** [comment]
I think this is already completed by @bagby  in #1249
