### ISSUE TITLE
Left Edge

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1315]
Left edge contains organization and meta navigation elements. 
- [x] Top button (cardstack logo) serves as "Home" button. It leads to home page (user's dashboard). 
- [x] Second button is user avatar. Clicking it opens left edge with log in/out controls. 
- [x] When user is not logged in it shows generic user icon. 
- [ ] When user is logged in it shows user's avatar

- [ ] **TBD**
>Next block is list of user's organizations. Clicking on organization opens left edge with inbox for that org and list of quick actions available. This block is optional, and may not be included on launch. 

- [x] At the bottom is the library button. It opens the bottom edge. 
- [ ] Second from the bottom is catalog button. It opens card catalog page.

![image](https://user-images.githubusercontent.com/1836666/73864210-4191b980-480f-11ea-9352-d01811a6453d.png)

- [x] Library button, while positioned at the bottom of the left edge, belongs to both bottom and left edges, so when the bottom edge is opened, library button retains its position on the bottom edge - it slides up with the bottom edge, covering the other buttons on the left edge, and with the open bottom edge it serves as "close library" button:

![image](https://user-images.githubusercontent.com/1836666/73308094-8739fb00-41ed-11ea-8dac-acfbae968517.png)

**Comment by burieberry** [comment]
Moving this back to to-do, since we can't yet do the remaining 3 items (different users, organizations, catalog page)
