### ISSUE TITLE
Investigate Github permissions

### ISSUE THREAD

**Issue by bagby** [cardstack/cardstack#1326]
Determine Github permissions capabilities, including but not limited to the following:

 * Can a user give permissions to Cardstack to create repos on the users' behalf?
 * Can user do the above and allow Cardstack to *only* modify those repo(s)?
 * Can a user give a very narrow set of permissions to Cardstack? This is important for optics, since users are unlikely to want to give broad permissions to a 3rd party.
 * Does the user need to provide their email address, or can they keep their email private and use a `noreply` email?

**Comment by jenweber** [comment]
https://developer.github.com/apps/about-apps/ has this diagram:

<img width="2300" alt="intro-to-apps-flow" src="https://user-images.githubusercontent.com/16627268/74476585-9d93b800-4e77-11ea-8883-e90452b8fecf.png">
