### ISSUE TITLE
Improved data source management for test suites

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#134]
Planning notes based a call with @habdelra:

The near-term plan:

1. Generic data source seeding
   - lets rename `seeds` to `data-sources`, because that's all that's really supposed to be in there. 
   - then we can use `seeds` for a more generic version of the ephemeral store's `initialModels`. You would manually load seed models into your data sources (_any_ data sources, not just ephemeral) by running a command line tool (`ember hub:seed`). 
   - By convention, the ephemeral store would still load effectively do `hub:seed` automatically at boot, so it behaves the same as today.
   - no more separate dev/test/prod directories for seeds (or data sources). We're finding it better to manage the distinction via env vars.
2. Postgres-specific seeding & testing
    - add command line tools for conveniently creating and destroying databases
    - create includes migrations (though they would still also run automatically if a running indexer sees that they're needed, as they do now).
   - the seed command from above would necessarily let you seed a postgres database, as long as it already exists.
   - `ember test` will require the database to already exist, it will not make it for you.
   - the baseline state between tests is a database that exists and has schema (from the migrations) but it does not include any automatic use of seeds.
   - each test is responsible for its own setup and teardown to get back into the baseline state.
   - the baseline state does not include seed models automatically, but individual tests can choose to load them explicitly (and then clean them up to get back to baseline)
3. Test Support package improvements
    - we need to expose a built-in privileged user for the clientside test-support code to run as, when setting up and tearing down tests
    - the existing test-support/addon/fixtures.js API needs to be extended to support data sources that can't do arbitrary checkpointing.  The `ephemeral-checkpoints` and `ephemeral-restores` data types would go away in favor a generic middleware provided by test-support that can create and restore checkpoints.
    - writers will get new hooks for creating and restoring checkpoints. Create is optional (not every data source can create arbitrary checkpoints). But you can implement restore without implementing create by supporting pre-defined checkpoints (how they are predefined is data-source specific configuration).
    - in the case of postgres, the "empty checkpoint" could be configured as a series of sql statement to run that get you into that state (mostly of the form "delete from some_table", but arbitrary sql is allowed in case your baseline state isn't truly empty).
        ```
        factory.addResource('data-sources', 'postgres').withAttributes({
          sourceType: '@cardstack/postgresql',
          params: {
            branches: {
              master: {
                migrationsDir: 'cardstack/migrations'
              }
            },
            testCheckpoints: {
              empty: [
                `delete from users`,
                `delete from batches`
              ]
            }
          }
        })


In the longer-term, we would like to make fully dynamic management of data-sources be a viable way of writing test suites. For example,`POST /api/data-sources` and `DELETE /api/data-sources/1` would actually create and destroy underlying resources like postgres databases or git repositories. This would let you drive arbitrarily deep testing all from a client-side test suite. This gives you the ability to do deep end-to-end testing to prove that an assumption holds, and elsewhere do shallower/faster testing based on the assumption.

**Comment by habdelra** [comment]
I have cycles to start tackling this I can start on the rename of `seeds` to `data-sources` if you haven't already.

**Comment by habdelra** [comment]
we did it! 🌮 🎉
