### ISSUE TITLE
When adding fields to the new card sometimes they get "stuck" and won't appear in the dropzone

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1342]
It seems like this happens only when trying to add field to the end of the form.
The field appears in the dropzone momentarily and immediately disappears until user moves a mouse. It's hard to find precise spot on which the dropzone will remain open. 
This behavior is inconsistent. 

![new field bug1](https://user-images.githubusercontent.com/1836666/74384575-8c877000-4dbf-11ea-8250-303ada86fb47.gif)

disregard the incorrect field being dragged - this is the side effect of #1341 - during the double  click scrolling motion has started after the first click and second click fell on another card.

**Comment by alexspeller** [comment]
This seems to no longer be a bug
