### ISSUE TITLE
field selection and drag and drop bug

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1343]
After several tries, if the field is selected with a mouse click (not dragged) and dropped back at the catalog, the last selected field is getting "sticky" - it follows the cursor even if another field is selected. Sometimes field selection changes but it's very hard to get field unselected, and the "sticky" field is displayed not under the cursor, but offset. On rare occasions, two fields are getting dragged, displayed in different positions on the screen. 
![field bug](https://user-images.githubusercontent.com/1836666/74385388-7084ce00-4dc1-11ea-8ba1-11c94a096a64.gif)

**Comment by alexspeller** [comment]
Could not repro after lots of click-mashing, looks like this is already resolved
