### ISSUE TITLE
Animate transitions when switching between layout and fields modes

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1348]
- [x] When switching from Fields to Layout, on the top edge "screen size" and "preview" buttons are sliding up off screen.
- [x] When switching from Layout to Fields, on the top edge "screen size" and "preview" buttons are sliding in down from the top of the screen.
- [ ] When switching between Layout and Fields, animate Right Edge in a similar way to #992
- [x] When switching between Layout and Fields, animate card resize in a similar way to #992 (more advanced animations would come later)

**Comment by burieberry** [comment]
Moving this back into the priority list for the remaining item, since the current animation work doesn't map exactly to the new hub
