### ISSUE TITLE
Update isomorphic-git versions

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1370]
In #1369, we are pinning to a git sha. Once the PR https://github.com/isomorphic-git/isomorphic-git/pull/1057 is merged upstream, we should update our dependency to use the released version.

**Comment by jenweber** [comment]
It looks like this change didn't make it into the new-hub merge. I opened PR #1441

**Comment by alexspeller** [comment]
Seems to be resolved by #1444
