### ISSUE TITLE
Deploy workflow doesn't wait for CI tests

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#1371]
It looks like test and deploy are setup in github actions as completely separate workflows, so we don't wait for tests to succeed before deploying.

cc @jenweber @alexspeller

**Comment by jenweber** [comment]
Took me a while to find this:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow
