### ISSUE TITLE
Initiating new card creation takes too long

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1388]
When creating a new card, it takes over 3 seconds to switch over to new card screen after either pressing "enter" on the keyboard, or clicking "create" button. 
![image](https://user-images.githubusercontent.com/1836666/75560586-71e60580-5a13-11ea-8156-0d1d91a72a7d.png)
In case of clicking a button this is not as confusing to the user as user is aware they clicked on the "Create" button, and there are some subtle visual cues - like the card name field losing focus (which are still not enough). But in case of keyboard navigation there is no visual indication that some action is taking place. 
In addition to longer term solution like improving the response time, we need to have a visual cue indicating to the user that his action is being processed. 

This ticked deals only with a short-term solution. 
- [x] Add a waiting indicator and a message to be displayed right after user clicked on "Create" or pressed "Enter", and to be disimissed when the new card screen is loaded. 

XD prototype: https://drive.google.com/open?id=1TlfOuLjSMUPcxA2O_4PLuGSb5yzPLl_r

**Comment by jenweber** [comment]
My initial thoughts are that we call `save` on the new card, and that blocks the transition to the new route. I'll also double check to see if we can render before the save completes.

**Comment by jenweber** [comment]
The way the app works, it seems that the save is required to complete before rendering the new card. If we don't await the save, it reintroduces a problem making new cards from the bottom edge.

@habdelra does it make sense to add a loading state here? Does your new-hub branch allow visiting the schema page for a card that has never been saved?

**Comment by habdelra** [comment]
Yeah it makes sense to add a loading state here. The new hub branch also assumes that the card has been saved an is addressable on the schema page for a card--this is not actually a requirement of the new hub, in the new API you can have a card that has no ID and still manipulate it. But rather, the way cardhost is designed currently--it would be _really_ difficult to refactor the app to allow cards to be edited without saving them first. the cardhost routes all make assumptions that the card has an ID, and those assumptions then flow into the components below. breaking those assumptions is possible, but a huge refactor of the system.

**Comment by jenweber** [comment]
Ok thanks! I will continue with this ticket as written.
