### ISSUE TITLE
When creating a new "Common card", new card dialog doesn't have "Cancel" button

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#1390]

**Comment by jenweber** [comment]
@dnaidionov I thought we wanted to delete the common cards, since they don't really do anything. Should I remove them, or fix this issue?

**Comment by dnaidionov** [comment]
let's fix the issue. right now they are just creating new base card, but when we have collections and layouts we will make those 3 cards adopted from base card, with slightly different behaviors, and we will be creating new card of that type.
