### ISSUE TITLE
Create a toggle for enabling autosave

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1414]
I think we should disable autosave by default in prod environments, given the roundtrip time for GitHub requests.

We should make a toggle that controls a query param (so that refreshing doesn't reset the toggle).

Thus would reintroduce a button, however.

**Comment by dnaidionov** [comment]
instead of a button we could place it in the context menu - that way less UI changes, less shifting other controls around

**Comment by jenweber** [comment]
This is relatively unnecessary with new-hub. Let's reopen if the new hub behavior seems to be too rough.
