### ISSUE TITLE
z-index of the context menu is too low

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1415]
<img width="813" alt="Screen Shot 2020-03-06 at 2 09 37 PM" src="https://user-images.githubusercontent.com/16627268/76114486-2f44a000-5fb4-11ea-9f56-c59fc9d34d6f.png">

**Comment by jenweber** [comment]
@dnaidionov can you see if this issue is still visible when you cast to the office TVs?

**Comment by dnaidionov** [comment]
depends on your settings - if you cast at higher resolution, the divs just don't overlap. But if you decrease it then yes, the above picture is valid

**Comment by jenweber** [comment]
Do you think it needs to be fixed by Friday?

**Comment by dnaidionov** [comment]
no, it's fine. we can always up the resolution
