### ISSUE TITLE
Local server error - "too many files"

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1420]
I did a brew update recently and it seems to have broken something for me. I get `EMFILE: too many open files, watch` and then infinite `2020-03-09 11:39 [2516] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)` if I try to start the Ember server for Builder (`yarn start-ember`). I uninstalled watchman altogether and that didn't seem to help.

The port stays occupied. The process is unkillable by `kill $(lsof -t -i:4200)`. It needs `kill -9 <pid>`.

Previous debugging from Will:

if you come across an error when starting the Cardhost app, along the lines of "Too many open files", try running watchman from the command line and see if it gives you any errors re: folder permissions. I've seen two variants of it: 1) the `/usr/local/var/run/watchman/<username>-state` folder is owned by root, in which case you can do something like `sudo chown -R /usr/local/var/run/watchman/<username>-state`, or 2) the `/usr/local/var/run/watchman/<username>-state` folder is owned by you, but is world-writable, then it suggests you do `chmod 0700 /usr/local/var/run/watchman/<username>-state`

**Comment by jenweber** [comment]
error log:

```
ENV Summary:

  TIME: Mon Mar 09 2020 11:46:35 GMT-0400 (Eastern Daylight Time)
  TITLE: ember
  ARGV:
  - /Users/jenweber/.nvm/versions/node/v10.17.0/bin/node
  - /Users/jenweber/cardstack/cardstack/packages/cardhost/node_modules/.bin/ember
  - s
  EXEC_PATH: /Users/jenweber/.nvm/versions/node/v10.17.0/bin/node
  TMPDIR: /var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/yarn--1583768786462-0.1451243632957797
  - /Users/jenweber/cardstack/cardstack/packages/cardhost/node_modules/.bin
  - /Users/jenweber/.config/yarn/link/node_modules/.bin
  - /Users/jenweber/cardstack/cardstack/node_modules/.bin
  - /Users/jenweber/.nvm/versions/node/v10.17.0/libexec/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/jenweber/.nvm/versions/node/v10.17.0/lib/node_modules/npm/bin/node-gyp-bin
  - /Users/jenweber/.nvm/versions/node/v10.17.0/bin/node_modules/npm/bin/node-gyp-bin
  - /Users/jenweber/.yarn/bin
  - /Users/jenweber/.config/yarn/global/node_modules/.bin
  - /usr/local/opt/terraform@0.11/bin
  - /usr/local/opt/terraform@0.11/bin
  - /Users/jenweber/.nvm/versions/node/v10.17.0/bin
  - /Library/Frameworks/Python.framework/Versions/3.8/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 3305381888
  TOTALMEM: 17179869184
  UPTIME: 1641
  LOADAVG: 2.275390625,3.15478515625,3.4033203125
  CPUS:
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  - Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz - 2300
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 35.1
  - http_parser: 2.8.0
  - icu: 64.2
  - modules: 64
  - napi: 5
  - nghttp2: 1.39.2
  - node: 10.17.0
  - openssl: 1.1.1d
  - tz: 2019a
  - unicode: 12.1
  - uv: 1.28.0
  - v8: 6.8.275.32-node.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: EMFILE
  - codeFrame: [undefined]
  - errorMessage: EMFILE: too many open files, watch
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [null]
    - line: [undefined]
  - message: EMFILE: too many open files, watch
  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
```

**Comment by jenweber** [comment]
Things  I tried:
- restarting my computer
- uninstall watchman
- `git clean -dfX` and reinstall node modules
- clear Embroider tmpdir

Trying next
- reinstall watchman
- check out earlier version of builder (right now I am on master)

The only thing I can figure that changed is that I did a brew update and updated my ember-cli version.

**Comment by habdelra** [comment]
that chown and chmod instructions from will is crucial. I had a the same problem and performing those steps resolved it for me.

**Comment by jenweber** [comment]
Reinstalling watchman seemed to do it, without any changes to the folder permissions.
