### ISSUE TITLE
Create an "adopt from this card" button on all cards

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#1461]
When I was making the video demo, there was no easy way to copy a featured card. I needed to modify the URL directly to go to the adopt endpoint.

We should add a button on each card that lets you do this. I think this is in a mockup somewhere.

**Comment by dnaidionov** [comment]
We talked about this with Chris and Gardella - this would be an item in the context menu. I think this way you could implement it right away without need for further designs. The only thing I would do is to group menu items and separate the groups - switch mode, actions, etc -  something like this: 
![image](https://user-images.githubusercontent.com/1836666/77082633-be997c80-69d2-11ea-8810-86297a46fb68.png)
At the moment actions would have a single item - to adopt a card.
