### ISSUE TITLE
Cardstack authorizer

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#16]
I'd open a PR, but I've been having trouble testing with local versions due to yarn & monorepo shenanigans.
Can we add this authorizer to `packages/authentication`? Right now I've had to define this in my app.
```js
import Ember from 'ember';
import Authorizer from 'ember-simple-auth/authorizers/base';

const { isEmpty } = Ember;

export default Authorizer.extend({
  authorize(data, block) {
    const accessToken = data.meta.token;

    if (!isEmpty(accessToken)) {
      block('Authorization', `Bearer ${accessToken}`);
    }
  }
});
```

**Comment by ef4** [comment]
@courajs thanks for this issue. We can definitely add this authorizer.

Also, please give local testing another try, I completely reworked it to use lerna and that process should have fixed the dependency bugs that you hit before.

**Comment by alexspeller** [comment]
@ef4 I've assigned this to me as I'm looking at the authentication stuff at the moment
