### ISSUE TITLE
Refactor grants so they dont default to "all"

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#181]
Right now when you create a grant, when the `type` or the `field` is not specified for the grant it is assumed to apply to all types or all fields. It makes it very easy to set a grant that casts too wide of a net if you omit information. It may be safer to take a more conservative approach such that the grant only applies to the types and fields that you specify. For convenience we could include an `all types` or `all fields` flag.

**Comment by ef4** [comment]
:+1:
