### ISSUE TITLE
Cardie deploy does not respect `ref` argument

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#2271]
The `ref` argument to the `!deploy` command doesn't have any effect.

There are two different places where changes are probably needed to fix this. The first is here:

https://github.com/cardstack/cardstack/blob/2ce9fb6ff8adc6b38e2c607ad601be6c3179ee57/packages/cardie/commands/deploy.ts#L62-L67

The `ref` argument here governs which version of the code will actually run within the workflow. It is always running the default branch, not the user's chosen ref.

The `inputs.ref` argument here *does* respect what the user asked for, but it gets passed ultimately into the deploy hub action here:

https://github.com/cardstack/cardstack/blob/2ce9fb6ff8adc6b38e2c607ad601be6c3179ee57/.github/actions/deploy-hub/action.yml#L5

which is never used. Instead of using it here, it would be better to remove this unused argument and not try to allowed the deployed version to diverse from the version running within the workflow.

**Comment by kdowlin** [comment]
@ef4 can I close this issue out? Looks like you got it fixed.
