### ISSUE TITLE
Have both `date` and `datetime` core types

### ISSUE THREAD

**Issue by bagby** [cardstack/cardstack#235]
Currently there is only a `date` core type, which actually behaves more like a `datetime`. It would be nice if we could have core data types for both `date`, where the time isn't important (ex. `2018-06-26`) and `datetime` (ex. `2018-06-26T04:00:00.000Z`).

**Comment by balinterdi** [comment]
We now have a `datetime-editor`, though not a `datetime` field type. Does that suit our needs?
