### ISSUE TITLE
Prevent editor view from appearing when there is no session

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#266]
When the user logs out, the editor view (right edge) is still displayed. We should not display the card editing view when the session is not authenticated.

**Comment by ef4** [comment]
This needs to be more subtle than described. Whether we’re showing the right edge is something that the cards themselves can have opinions about, and it depends on the permissions on the current card.

**Comment by habdelra** [comment]
Makes sense. How about if the session has a grant that allows editing of any field on the card(s) shown, or ability to create a new content type?
