### ISSUE TITLE
Editing relationships

### ISSUE THREAD

**Issue by knownasilya** [cardstack/cardstack#33]
Dump from @ef4 on Slack, before it moves into the nether.

> I don’t think there’s much downside to representing the enum as a relationship. It may seem more verbose, but it allows us make it less special. You would want a clear way to query, filter, and sort the choices anyway, and if they’re real resources in their own right you already have all that for free.
We can design good UI to make it all feel natural from the user’s perspective.

>  the general rule right now is that any resource gets edited and saved by visiting its own canonical URL. Content that’s embedded from elsewhere isn’t edited directly. I think this is a good rule, and we can allow more contextual editing of embedded content by having something like a modal card view (imagine clicking on a piece of embedded content and the content animates to float in front of the original page, where you can edit & save it and then let it go back into place.)

Basically, there are two edit modes, change the relationship to another existing entity (or delete it altogether) or edit the current entity. The first one will require finding all valid entities of that type, which might not always be via a `findAll`. Both modes of editing need to be easy to understand and do from the UI side.

**Comment by knownasilya** [comment]
Didn't know you were a Cardstack contributor @lukemelia

**Comment by lukemelia** [comment]
@knownasilya Yapp Labs has been helping out with the project since January. It's been great to work with the team, and we're going to be building out a brand new version of card architecture in this repo, hence the spring cleaning!

**Comment by knownasilya** [comment]
Any info about this new architecture?

**Comment by lukemelia** [comment]
Nothing consumable yet, but stay tuned!
