### ISSUE TITLE
Upgrade packages to Ember 3.4

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#332]
From @ef4 

> I don’t think ember-cli-update quite works for monorepos, but you can hack around that by moving directories around before and after running it.
> or lets fix ember-cli-update

**Comment by habdelra** [comment]
The `@cardstack/data` package is on Ember 3.4 and using `async`/`await` in the browser. Feel free to use it as a reference. (it was actually pretty painless, mostly a `package.json` update).
