### ISSUE TITLE
Show some sort of status to the user while a card is being created or updated

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#346]
Now that we have a remote git-datasource that does not respond until the data is committed remotely it is very clear that we need to give some feedback to the user when creating or updating a card.

In my personal testing I have seen a case of multiple seconds before the network responds but there is currently no `loading` message once you submit the form in the tools.

**Comment by marcoow** [comment]
@dnaidionov: are there mockups that we could rely on for building this?

**Comment by marcoow** [comment]
In the first iteration of this, we'll just show some sort of loading spinner somewhere in the editor while async stuff is happening (without disabling anything or so).

**Comment by jorgelainfiesta** [comment]
I'll give this a shot while I wait for some answers on my other issue.
