### ISSUE TITLE
Implement includeInDocumentSearch flag for fields to control inclusion in full-text search

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#396]
**Edit:** This issue has been updated to reflect the conversation in https://github.com/cardstack/cardstack/pull/445 and other use-cases surrounding searchability have been extracted into the issues #465 and #464 

Each field should have an `includeInDocumentSearch` boolean attribute that indicates whether it should be included in the combined full-text search. In this context combined full-text search is different from [field-level full-text search](https://github.com/cardstack/cardstack/issues/464) in that it is just powered by the query implementation of a searcher `{ query: 'some words' }` and searches recursively through relationships. 

Our combined full-text search index (the `q` column) should only include fields that are marked with the `includeInDocumentSearch` tag. It should _recursively_ include searchable fields, meaning that _if and only if_ a relationship field is searchable, than the searchable fields from the related resource(s) are also included.

**Comment by marcoow** [comment]
@mansona: I assume this is replaced by #465 now?
