### ISSUE TITLE
Git seeds cause implicit dependency on authentication

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#4]
The development seeds cause `ember serve` to fail when `@cardstack/authentication` is not installed.

https://github.com/cardstack/cardstack/blob/master/packages/git/blueprints/cardstack-git-seeds/files/cardstack/seeds/development.js#L25

1. `ember new my-app --yarn`
2. `yarn add @cardstack/hub @cardstack/git`
3. `yarn add dag-map` to work around #3 
4. `ember generate cardstack-git-seeds`
5. `ember serve` results in:
```
🚀 my-app$ ember serve
Livereload server on http://localhost:49153
(node:58110) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module '@cardstack/authentication/package.json'
Error: Cannot find module '@cardstack/authentication/package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at loadPlugin (/Users/aaron/dev/my-app/node_modules/@cardstack/hub/plugins.js:124:41)
    [ snip ]
```

Deleting the plugin config for authentication from `cardstack/seeds/development.json`:
```
  {
    type: 'plugin-configs',
    id: 2,
    attributes: {
      module: '@cardstack/authentication'
    }
  },
```

lets the app run

**Comment by ef4** [comment]
Good catch. 

Perhaps the seeds should be a directory, not a single file, and then each module could provide it's own non-conflicting blueprint to generate good default seeds.

**Comment by courajs** [comment]
That sounds like a great idea

**Comment by ef4** [comment]
I think this is resolved now (seeds is a directory, and each plugin that has seed generators is only referring to itself).
