### ISSUE TITLE
Right edge needs vertical scroll

### ISSUE THREAD

**Issue by burieberry** [cardstack/cardstack#417]
We added the scroll to "Add New" panel, but not on this panel. Can't see the "Add Card" button below because can't scroll.

<img width="321" alt="right-edge-cant-scroll" src="https://user-images.githubusercontent.com/16160806/48079117-aac3f080-e1b8-11e8-92a9-5de7d394a8ed.png">

**Comment by jorgelainfiesta** [comment]
This was done in #425, thanks @burieberry!
