### ISSUE TITLE
4 Edges: Bottom Edge starting styles

### ISSUE THREAD

**Issue by jorgelainfiesta** [cardstack/cardstack#439]
We are starting to re-skin `tools` to embrace the new 4 edges design. This task is limited to write the styles and markup necessary to implement the specs provided for the bottom edge. Any new features or changed functionality of the bottom edge will be treated as separate tickets. 

- [x] The `.sketch` file will be provided by @dnaidionov

Let's start by building first the structural styles of the pieces that conform the bottom edge. At the moment, the only part that actually can use real data are the cards fetched by the search query. The other buttons and links are just mocked.

Formerly, there was no visible part of the bottom edge when it was turned off. However, now there is a collapsed view and an expanded view. 

**Collapsed view**

Currently there is nothing rendered on the collpased view. The search header will have to be taken out of the expanded view so it's also visible in the collapsed view. There is also another element called "Light box" that is visible in this state, but it's an entirely new feature that we'll address in the future. 

<img width="1010" alt="screen shot 2018-11-21 at 2 42 31 pm" src="https://user-images.githubusercontent.com/4451393/48845163-19e63b00-ed9c-11e8-9110-d379a8b4cc4d.png">

**Expanded view**

The resulting opened state would look something like this (note that now the expanded bottom edge has a 100% height of the view port): 
<img width="987" alt="screen shot 2018-11-21 at 2 23 56 pm" src="https://user-images.githubusercontent.com/4451393/48844109-3c2a8980-ed99-11e8-9c2c-f48380256070.png">

No other state is expected to be styled in this issue (ie. advanced search, toggle list and search view, etc). Once we have this common base we'll hopefully be able to do more parallel development on the bottom edge features and styles. 

Clarifications:
- [ ] Should the grid scroll keep the search header sticky as "Grid scroll A" seems to suggest in the sketch file? Or will it scroll with the rest of the cards as "Grid scroll B" shows?

**Comment by dnaidionov** [comment]
Bottom edge designs uploaded to trello: https://trello.com/c/UQCeV9Ep/43-latest-sketch-files#
