### ISSUE TITLE
4 Edges: Right edge composition panel styles

### ISSUE THREAD

**Issue by jorgelainfiesta** [cardstack/cardstack#440]
We are starting to re-skin `tools` to embrace the new 4 edges design. This task is limited to write the styles and markup necessary to implement the specs provided for the right edge. Any new features or changed functionality of the bottom edge will be treated as separate tickets. 

The `.sketch` file is available in Trello: https://trello.com/c/UQCeV9Ep/43-latest-sketch-file

For this issue, we will focus on re-styling what we already have on the right edge. Meaning, applying new styles to `.cs-active-composition-panel` so it adopts the new designs:

<img width="209" alt="screen shot 2018-11-14 at 3 49 28 pm" src="https://user-images.githubusercontent.com/4451393/48490818-873b1e80-e826-11e8-9bd2-7c6eadec28a3.png">

I've annotated the screenshot with a red line to express the parts of the design that we should skip for now, as we do not support these features yet.

I think the result of this issue should look something like this:
![result](https://user-images.githubusercontent.com/4451393/48491570-2d3b5880-e828-11e8-8a24-c018d74769f4.png)

**Comment by burieberry** [comment]
@jorgelainfiesta let me know if this looks good to merge

**Comment by marcoow** [comment]
We'll create follow-up issues as we recognize bugs or things to improve.
