### ISSUE TITLE
After creating and saving a new card, the route still shows "/new" instead of card id

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#446]
When user starts creating a new card, the route is set to `/cards/<content-type>/new` - e.g. `/cards/tags/new`. After successfully saving the card the expectation is for the route to change from `new` to card id, but this doesn't happen.

**Comment by habdelra** [comment]
The ultimate goal here is that when we create a new card it appears in a modal. In this manner the new card does not effect the URL until after it is saved. And the resulting URL will be an actual URL and not `.../new`. The prerequisite to this work is completing the new routing system.

**Comment by dnaidionov** [comment]
Closing
