### ISSUE TITLE
We need a way to mark fields as unique across their content type. 

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#447]
When creating content type developers should be able to designate field as unique. 
Uniqueness should be defined within organization. 
Because information for a field could be aggregated from multiple data sources we cannot enforce strict uniqueness. However, we can soft enforce it, meaning if an entry already exists we will not allow user to create another one with same unique attribute. But we will not enforce uniqueness on already existing data. 

**E.g.:**
User is a member of both `cardstack` and `dotBC` organizations. Both have content type `tag` with `name` field defined and that field is marked as unique. User should not be permitted to create a tag in `cardstack` with a names that already exist in it. But if a tag with this name exists in `dotBC` but not in `cardstack` user should be allowed to do that.

**Comment by ef4** [comment]
This isn't really actionable as written, the concept of indices with clear boundaries does not exist and I'm not completely sure we'd want it to. We should plan to discuss in more detail.

**Comment by ef4** [comment]
I think I can restate this in a way that works: content types need to be globally distinct. This is a thing we are already planning. 

And then fields could be require to be unique per content type. Although that is also not simple to achieve in a distributed system, short of delegating to one of the blockchain data sources.

**Comment by dnaidionov** [comment]
After discussing issue with @ef4 i changed user story.

**Comment by mansona** [comment]
@dnaidionov when you're talking about "organisations" in this context, is it ok to assume that you just mean "across datasources" i.e. you have multiple datasources configured that may be resulting in "soft" conflicts in uniqueness constraints

**Comment by dnaidionov** [comment]
Actually, it's more than that. 

- First, user can work on multiple cardstack based websites that are not related to each other and belong to different owners, and maybe even run on different physical deployment nodes - that's organization. 
- Second, within the same organization, we may aggregate data for certain data type from different data sources - e.g. let's say we have `tags` that are merged from 2 sources - our local PostgreSQL database and cardstack-daily-news.com/api/tags/list. In this case same tag might exist in both datasources, and we will not try to resolve existing conflicts, however if user tries to create another instance of tag existing in either source, we should prevent this. But if a tag existing in one system gets added to another by some external means - we can't prevent that.

**Comment by dnaidionov** [comment]
No, this is something that still needs to be designed. To enable this we would also need some kind of cardstack-SSO solution. 
The simplest case is that each organization is deployed completely separately. But it's not exactly clear what happens if 2 "organizations" are deployed on the same hub, or even if that can be done given that we might require complete data separation for whatever reasons - e.g. legal. 
As Ed mentioned above: 
> the concept of indices with clear boundaries does not exist and I'm not completely sure we'd want it to. We should plan to discuss in more detail.
So currently we proceed with the assumption that "organization" is deployed on its own instance of hub and doesn't share it or indices with others.
