### ISSUE TITLE
Issue with ember-source version

### ISSUE THREAD

**Issue by jorgelainfiesta** [cardstack/cardstack#450]
With @mansona, we observed very unexpected behaviors happening with `cardstack/edges` when trying to use it in a dummy app for `cardstack/card-picker`. The edges would not be rendered, but no errors would be yielded.  After a lot of experimentation, we discovered that the cause of problems was the version of `ember-source` being used, which was `~3.4.0`. If the app uses `ember-source` `~3.2.0`, the edges work as expectedly. 

When isolating this problem in a new branch, the errors that we get are:

 ```
Uncaught Error: Could not find module ember-glimmer/syntax
```
and
```
Uncaught Error: Could not find module `ember-resolver` imported from `dummy/resolver`
```

This issue can be reviewed in this branch https://github.com/simplabs/cardstack/tree/ember-source-issue by running `yarn start` in `packages/tools`.

**Comment by Turbo87** [comment]
the second issue is related to https://github.com/thefrontside/ember-let/issues/49 and can be fixed by moving to `ember-let-polyfill` instead of using `ember-let`, which seems to be safe as we don't use the inline let form at all.
