### ISSUE TITLE
Move applyReadAuthorization to DocumentContext

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#454]
This is a refactor Ed suggested [here](https://github.com/cardstack/cardstack/pull/421#discussion_r235066761).

We'll wait for Will to complete the task which implements a related refactoring so that this becomes easier.

**Comment by balinterdi** [comment]
Waiting for #438 to be complete.

**Comment by bagby** [comment]
@balinterdi #438 is completed.

**Comment by balinterdi** [comment]
See #543
