### ISSUE TITLE
Refactor cardstack-data#validate to use `relatedOwnedRecords`

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#482]
https://github.com/cardstack/cardstack/pull/479 implements a method on all cardstack model objects called `relatedOwnedRecords` that returns all of its related records for the model. That should be used to clear up the `validate` method in the `cardstack-data` service where we basically reimplement `relatedOwnedRecords` inside the function.

**Comment by dnaidionov** [comment]
done!

**Comment by balinterdi** [comment]
This should be fixed by #493 (when that's merged).
