### ISSUE TITLE
A field is not considered "writable" if the read grant and write grants are provided by different grants

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#494]
I noticed this issue when I was trying to set up a github-user grant where logged in users have the ability to edit and create resources but everyone else is able to read only.

I was also using mock-auth at the time but I'm not sure it's relevant 🤔 

When configuring my grants like this: 

```
  factory.addResource('grants')
    .withRelated('who', [{ type: 'groups', id: 'everyone' }])
    .withRelated('types', contentTypes.concat([
      { type: 'content-types', id: 'content-types' },
      { type: 'content-types', id: 'spaces' }
    ]))
    .withAttributes({
      'may-read-resource': true,
      'may-read-fields': true,
    });

  factory.addResource('grants')
    .withRelated('who', [{ type: 'groups', id: 'github-writers' }])
    .withRelated('types', contentTypes)
    .withAttributes({
      'may-create-resource': true,
      'may-update-resource': true,
      'may-delete-resource': true,
      'may-write-fields': true,
    });
```

I was not able to edit any fields on existing or new resources. 

When I added a `may-read-fields: true` line to the `github-writers` grant then it started working even though conceptually I should have had the `may-read-fields` permission already.

My theory is that this logic that is building the `writableFields` [here](https://github.com/cardstack/cardstack/blob/master/packages/hub/searchers/permissions.js#L63) is accidentally relying on both permissions being available on the same grant (but I'm not sure)

**Comment by balinterdi** [comment]
This should have been fixed by #471 which was merged into cardstack master 6 days ago. Are you using a version which includes that fix? (if you do, I'll check this again)

**Comment by mansona** [comment]
Thanks for that @balinterdi, I had a feeling you would know exactly what was going on 😉 

It looks like the latest version of `@cardstack/hub` was released [13 days ago](https://www.npmjs.com/package/@cardstack/hub). If someone could do a release then we can update and check if it's still an issue 👍

**Comment by balinterdi** [comment]
@mansona When you have some down time :) could you check if this has indeed been fixed by the latest release?
