### ISSUE TITLE
Add an after-first-indexing promise

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#496]
Some plugins need to do things after the first successful `indexers.update()`.

One example is [this code](https://github.com/cardstack/cardstack/blob/c4caae453d2af28df6916e8dd26d8e7f849aab40/packages/hub/main.js#L58-L80) which really belongs back in `@cardstack/ephemeral`.

Another example is precalculating `getRoutersInfo` in `hub/routers.js` (today we do it lazily on the first request, but we could start it immediately after first indexing).

**Comment by jenweber** [comment]
Is the main work here that [this code](https://github.com/cardstack/cardstack/blob/c4caae453d2af28df6916e8dd26d8e7f849aab40/packages/hub/indexers.js#L95) in `indexers.js` should return a promise instead of returning nothing?

```
  async update({ forceRefresh, hints } = {}) {
    await this._setupWorkers();
    // Note that we dont want singletonKey, its inefficient due to the sophisticated invalidation we are using,
    // also we dont want to use singletoneNextSlot, since all the indexing calls are important (as they can have different hints, and we dont want to collapse jobs)
    await this.jobQueue.publishAndWait('hub/indexers/update',
      { forceRefresh, hints },
      { singletonKey: 'hub/indexers/update', singletonNextSlot: true, expireIn: '2 hours' }
    );
  }
```

**Comment by ef4** [comment]
No, and that code already does return a promise, just by virtue of being `async`.

The issue is that we want other plugins to be able to do things after that promise resolves, without themselves needing to call the method.

There are quick and simple solutions to this problem, like adding a `ready()` method to hub/indexers.js that would return a promise that resolves at the appropriate time. But I think that may be too literal, and ties plugins to our current implementation.

I wonder if we couldn't just figure out which methods these plugins want to call that shouldn't really run until after first indexing is complete, and make those methods _automatically_ wait for the first indexing to finish.

**Comment by jenweber** [comment]
I looked to see which places indexers were used that showed signs of delays, to get an idea of what kinds of things require waiting. It seems like model validation might be the main thing.

The EphemeralStorage constructor in `ephemeral/service.js`. It takes a callback to know when the validators can run:

```
  constructor(indexers, validatorHook) {
    // map from `${type}/${id}` to { model, isSchema, generation, type, id }
    // if model == null, that's a tombstone
    this.models = new Map();
    this.blobs = new Map();
    this.indexers = indexers;

    this.checkpoints = new Map();

    // We can't validate right at startup, because we need to let all
    // the indexers reach a working state before we can tell if our
    // models are consistent with all the rest. So we allow a hook for
    // delayed validation.
    this.validatorHook = validatorHook;
  }
```

In `hub/indexers.js`:
```
  async _setupWorkers() {
    if (!this._workersSetup) {
      await this.jobQueue.subscribe("hub/indexers/update", async ({data: { forceRefresh, hints }}) => {
        await this._doUpdate(forceRefresh, hints);
      });
      this._workersSetup = true;
    }
  }
```

In `ethereum/cardstack/transaction-indexer`. This might be unrelated?

```
  async start(addressIndexing, ethereumClient, jsonRpcUrls) {
    log.debug(`starting transaction-indexer`);

    log.debug(`waiting for pgsearch client to start`);
    await this.pgsearchClient.ensureDatabaseSetup();
    log.debug(`completed pgsearch client startup`);

    this.addressIndexing = addressIndexing;
    await this._startTrackedAddressListening();

    this.ethereumClient = ethereumClient;
    await this._ensureTransactionIndexStarted(ethereumClient, jsonRpcUrls);

    this._hasStartedCallBack();
    log.debug(`completed transaction-indexer startup`);
  }
```

**Comment by jenweber** [comment]
Options:
- track "first indexing state" and poll to see if it's finished. When should the value get reset? Alternately, does an instance the initializer class get recreated on each use? If so, no reset would be necessary.
- create an EventEmitter. Should think through race conditions. What if something is waiting for an event that already happened?

An example of state tracking on the class is `_ensureTransactionIndexStarted` in `transaction-indexer`, which uses a Promise-based loop to wait until things are ready. However this depends on actually running the operation to know if it's done, which isn't what we want to do:

```
  async _ensureTransactionIndexStarted(ethereumClient, jsonRpcUrls) {
    if (this._transactionIndexHasStarted) { return; }

    if (!this._transactionIndexPromise) {
      this._transactionIndexPromise = this._startTransactionIndex(ethereumClient, jsonRpcUrls);
    }
    await this._transactionIndexPromise;

    this._transactionIndexHasStarted = true;
  }
```

**Comment by jenweber** [comment]
The two of us looked at this together and there's not a quick win. It's not a high priority either, so we're putting this on the back burner for now, but it should still be addressed at some point.
