### ISSUE TITLE
Cards returned from the data service don't possess enough information to be able to navigate to an isolated view of the cards

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#505]
The cards returned from the data service don't possess enough information to be able to navigate to an isolated view of the cards. Specifically they are missing the `self.link`. I think it is important that cards returned from the data service can be isolated. This is probably a pretty big use case, as it is necessary to support a user search for cards.

The `spaces` instance is the model for the cardstack.content route. Presumably the data service can get a handle on the current space using ember's routing service. I think it might be a good idea for the data service to leverage the current spaces context when performing a search so that the cards returned contain self.links and can then be isolated by the client in the current spaces context.

**Comment by ef4** [comment]
This is concerning also from a caching perspective. Both in terms of HTTP caching, and our search index (it's probably bad if we are assigning self links to every resource during a GET, as opposed to having most of the work precached during indexing).

Perhaps we shouldn't try to allow a single card to have different self links within different spaces on the same site. It does seem like a violation of spirit of canonical URLs. I know this interferes with what we said about site composability (cards from disparate authors may have different opinions about what the canonical URL for the same card is).

Ideas:
 - I think the most common case is that a given card only has a self link in one space anyway, in which case that can just always be its self link.
 - in the rarer case where there are spaces with conflicting opinions, we could have a priority rule and let one win. The rule could favor card router that are closer to the site root card, with an alphabetical tie breaker.

Do we already have cases where these additional constraints would be problematic?

**Comment by ef4** [comment]
If we can live with these constraints, then the self links can go directly into the search index and all the requests whether via spaces or via the data service will see the same thing.

**Comment by ef4** [comment]
I just realized that we are probably not using `self` links in a way that is json:api spec compliant.

They are supposed to point at the json:api endpoint for the resource, which for us is a different URL than the card's space.

**Comment by ef4** [comment]
An alternative to picking a single self link for each card is to include all of them side-by-side (using meta now, not links). Then the cardstack-url helper could pick the one that is "closest" to where the user is coming from, by some metric.

**Comment by ef4** [comment]
```
{
  data: {
    type,
    id,
    attributes,
    meta: {
      'cardstack-spaces': ['/deck/i-live-here', '/dotbc/and-also-here']
    }
  }
}
```

**Comment by habdelra** [comment]
I like the 2nd proposal where the card is able to describe all of the spaces it resides within. that seems more true to the idea where a card is supplying its own router and making decisions around the URL namespace what it is mounted within

**Comment by habdelra** [comment]
yeah, and agree on the self.link observation. totally lets move it to meta
