### ISSUE TITLE
Clear up cs-active-composition-panel template

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#518]
The template is getting long and though it's not obvious how to break it to smaller pieces (mostly because the difference between how we render `renderedFields` and `modelFields` there are a few things we can do to make it more readable:

* Create a helper for concating the `errors` class
* Move boolean logic into the component (e.g `cs-field-editor`)
* Stretch goal: move fetching permissions into the component where it's needed. Currently we fetch permissions to the "content" and all related, owned records and pass down the appropriate permissions object for those records from the top. If we did it in lower-level components, we might be able to get rid of the `cs-uid` setting, too.

**Comment by balinterdi** [comment]
@ef4 Other than that, #528 is ready for review.

**Comment by mansona** [comment]
@balinterdi can you create a separate issue that covers the "third bullet point" above please? I guess we can discuss the merits the implementation in that new Issue and we can close this one 👍

**Comment by balinterdi** [comment]
Good idea, I did just that: https://github.com/cardstack/cardstack/issues/566
