### ISSUE TITLE
Merge cardstack-data#getCardMetadata to getCardMeta

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#519]
We have two methods for the same thing, living on the same object (the cardstack-data service). We should rewrite the only place `getCardMetadata` is called from to use `getCardMeta` as that's the method we want to use going forward.

See #521

**Comment by marcoow** [comment]
I'm not sure these methods are for the same thing although they are similarly named of course. `getCardMeta` seems like being used for getting a string identifier for a card (something like a custom `toString`?) while `getCardMetadata` is meant to be the way to get arbitrary metadata for a card. The current implementation is really just a placeholder but the idea is that as we have that now, we can change how this works under the covers, potentially with an implementation as sketched out here: https://github.com/cardstack/dotbc/issues/156#issue-391796369

**Comment by balinterdi** [comment]
We'd discussed this with @ef4 and we want a single method on the service that restrains the "public API" of cards.

`getCardMetadata` gives you anything which is undesired while `getCardMeta` only allows a set of meta attributes (that should be extended as we have requirements). We still reach into cards in some places and we should get rid of these and move them to `getCardMeta`.

**Comment by ef4** [comment]
Yes, these two methods are supposed to be doing the same thing. They just take very different approaches to filling in an initial basic implementation.

It's better if we can be explicit about what metadata fields are in use (more like the current getCardMeta), but if we need to fall back to the card's own field of the same name (like the current getCardMetadata) as a temporary measure that would be OK.

**Comment by balinterdi** [comment]
> It's better if we can be explicit about what metadata fields are in use (more like the current getCardMeta), but if we need to fall back to the card's own field of the same name (like the current getCardMetadata) as a temporary measure that would be OK.

And that's exactly what the PR does in #521 (providing the fallback with the comment that this should only be temporarily allowed).
