### ISSUE TITLE
Figure out a way to test that the `?branch=` queryParam is being passed correctly to the server

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#532]
This is a follow-on issue from https://github.com/cardstack/cardstack/pull/531

The problem that we face is that the adapter `@cardstack/models/adapter` is not resolvable directly in a test because it is used as the source of codegen for hub types. We would need to do some sort of acceptance test so that a real adapter is generated for us and then ensure that the branch query param is included on the network request 👍

**Comment by ef4** [comment]
A more complete acceptance test would be fine, but so would:

```
import Adapter from '@cardstack/models/adapter';
import { setupTest } from 'ember-qunit'
import { module, test } from 'qunit';

module('something', function(hooks){ 
  setupTest(hooks);
  hooks.beforeEach(function() {
    this.owner.register('adapter:my-test', Adapter);
  });
});
