### ISSUE TITLE
Git data source: Make index consistent after manually editing underlying git repo

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#545]
_Originally posted by @habdelra in https://github.com/cardstack/dotbc/issues/131#issuecomment-447128581_

> upon deeper thought i think we'd actually need an `ops.replaceAll()` mechanism for us to hook into if we want to make the index consistent again after manually editing the underlying git repo....

I guess this belongs in cardstack repo. 
Also, we need to make sure other data sources will not have similar issues

**Comment by habdelra** [comment]
I think this will go away once we start creating branches and patch documents in branches via the hub. The

**Comment by mansona** [comment]
Closing in favour of https://github.com/cardstack/dotbc/issues/197
