### ISSUE TITLE
got api-validation error when saving data

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#552]
On the master recording screen changed title and clicked Save. The changes were saved to GitHub, but I also received following error from https://hub.jorts.surgery/api-validate/master-recordings/jumpin-jack-flash-recording : 
```
{
  "errors": [{
    "title": "Bad Request",
    "detail": "missing required field \"id\"",
    "code": 400,
    "source": {
      "pointer": "/data/id"
    }
  }]
}
```
reminds me of cardstack/deck#250

**Comment by marcoow** [comment]
@dnaidionov I cannot reproduce this. It might be fixed already, can you check again? Maybe I'm just mis-understanding what you did.

**Comment by dnaidionov** [comment]
@marcoow This is still happening - i recorded screencast to reliably reproduce the issue - you can follow the same steps on any song. This is for codes, but the error is happening on other fields too

https://www.useloom.com/share/e54fc408f73c4af38059c4e10e49d0d5
