### ISSUE TITLE
Allow seeding images (when using the `cardstack-image` type)

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#564]
Replacing a URL-based image (where simply the src URL is given as a string) with the 1st class image support via the `cardstack-image` type greatly enhances the user experience but unfortunately we can't yet seed an image that way as it's not just a matter of using a URL.

To enable this, we'd have to upload the image during boot / set up, probably by calling `handleCollectionPostBinary` in the jsonapi middleware:

https://github.com/cardstack/cardstack/blob/master/packages/jsonapi/middleware.js#L284-L299

**Comment by bagby** [comment]
Implemented by #706
