### ISSUE TITLE
hyperledger error is recorded in the log on every data update

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#573]
Every time we update data in the dotbc UI a hyperledger error is recorded in the logs.

e.g.: 
https://papertrailapp.com/groups/8848161/events?focus=1017876193908813833&q=%28sender%3Adotbc-staging%29+%28exception+OR+Exception+OR+error+OR+Error%29+-%28%22error-card%22%29&selected=1017876193908813833
```
Jan 04 11:03:38 dotbc-staging_94f086581179 node.log:  cardstack/git-hyperledger Error pushing to hyperledger blockchain: TypeError: Path must be a string. Received null - Path must be a string. Received null
```

**Comment by mansona** [comment]
this will be fixed as a result of another issue 👍
