### ISSUE TITLE
Make ember data include the branch id in the content's type

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#580]
In order to be able to store instances of the same models from different branches in the same Ember Data store, we must include the branch name in the model's `type`. If e.g. a user edited `posts:1` on their own branch and switches to another branch where `posts:1` has different attribute values, we should still be able to keep both in the Ember Data store so we could e.g. show a diff of the 2 instances.

We do not want to expose this custom model name (that includes the branch) via the API or to users of the `cardstackData` service. Thus, we need to

- [x] translate between API types and model names in the serializer
- [x] translate between defined model names (without branch) and Ember Data internal model names (with branch) in the `cardstackData` service

### Open Questions

- [x] the model files are generated by Cardstack as `@cardstack/models/generated/<model-name>`, e.g. `@cardstack/models/generated/release-general-info`; how do we map these model implementations to the actual models that we would want to be called e.g. `master-release-general-info` or `my-branch-release-general-info` then? **Answer: We don't map - we simply create modules for every model and branch as `@cardstack/models/generated/<branch-name>-<model-name>` (that can even be done on the fly via the `codegen` service).**

**Comment by marcoow** [comment]
> This is a placeholder issue that @ef4 will fill out with more specifics

@ef4 👆😉

**Comment by ef4** [comment]
The server API should stay as it is: branch is a query param. 

Our ember data adapter and/or serializer (in the models package) should be extended so it rewrites the incoming documents such that the branch gets encoded inside the `type` field that ember data uses. And it should do the reverse transformation when serializing back out to the server. 

Users of the cardstack data service will still ask it for the real type, and the service will combine that with the branch before asking ember data for records. 

I think we already have a helper for getting the type of a model, for the case where somebody is introspecting. 

The goal is to hide this “concatenated type” as internal, and all our public APIs used by cards just see the real type (and branch).

**Comment by marcoow** [comment]
Ok, I think I get it - I have the feeling that this will require a bit of research and investigation though. I'll update the issue description.

**Comment by marcoow** [comment]
I created a small demo project that supports different versions of the same model at the same time: https://github.com/simplabs/multi-branch-ember-data

![ui mov](https://user-images.githubusercontent.com/1510/52421066-98c55700-2af3-11e9-8d5f-ea67afcf65a6.gif)

This requires one module per supported model (in this case only 2 are supported and the modules are generated up-front: https://github.com/simplabs/multi-branch-ember-data/tree/master/app/models). With Cardstack though, we have access to the [`codegen` service](https://github.com/cardstack/cardstack/blob/master/packages/codegen/app/services/cardstack-codegen.js) that would allow us to generate these modules (all as re-exports of the actual models) on the fly during runtime.

**Comment by marcoow** [comment]
I did the research for this and think it's all doable without any major blockers. We would only actually need to do this in order to build the diff view that would be shown before merging though as otherwise we'd never have to have different versions of the same model from different branches in the store. I'd advise against trying to build the diff view and instead focus on the actual merge feature first to increase the probability of having that in time for the demo. That would also mean not actually doing this for now.

What do you think @dnaidionov? I think we need to focus all of our efforts on getting the basic merge feature done and I can't see that we'd have the diff view for the demo on the 25th as well.

**Comment by dnaidionov** [comment]
yes, merge functionality first, diff views later.
