### ISSUE TITLE
Add transitionToContentPage to routing service

### ISSUE THREAD

**Issue by balinterdi** [cardstack/cardstack#59]
I've found myself writing the following snippet more than once (ok, twice :) ) to go to the page of a resource (a cardstack model):

```js
import routingService from '@cardstack/routing/services/routing';
import { transitionTo } from '@cardstack/tools/private-api';
import { getOwner } from '@ember/application';
import { pluralize } from 'ember-inflector';

export default routingService.extend({
  transitionToContentPage(resource) {
    let routingId = resource.get('id');
    let routeName = pluralize(resource.constructor.modelName);
    let { name, params, queryParams } = this.routeFor(routeName, routingId);
    queryParams.routingId = routingId;
    return transitionTo(getOwner(this), name, params.map(p => p[1]), queryParams);
  }
});
```

I think it'd be valuable to add this method to the routing service as it's what users will most often want instead of calling service.routeFor, assembling all the params correctly and transitioning to the new route, none of which is obvious to do.

**Comment by venkatd** [comment]
I had to deal with redirecting to a model too. Good idea.
