### ISSUE TITLE
git indexer doesn't seem to be able to handle merge commits

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#596]
After much investigation it appears that this issue, https://github.com/cardstack/dotbc/issues/197, seems to be related to using merge commits. It appears as though the git indexer is unable to handle these.

Unsure about this issue, https://github.com/cardstack/dotbc/issues/163, it might be the same underlying scenario (?)

**Comment by mansona** [comment]
I don't think https://github.com/cardstack/dotbc/issues/163 is the same underlying issue 🤔 my impression about that one was that the index wasn't getting **anything** from git at all, even on a clean branch. But of course, it would be worth double checking 😂

**Comment by marcoow** [comment]
Is this actually going to block the merge request workflow for dotBC? cardstack/dotbc#356

**Comment by habdelra** [comment]
I wonder if the answer here is to stop using node-git, and start using isomorphic git?

**Comment by ef4** [comment]
I don't doubt there is some real bug here, but it seems unlikely to be "can't handle merge commits".

Indexing only looks at the head of a branch, and it doesn't care how you got there, so merges are not really a thing it would notice.
