### ISSUE TITLE
fetchPermissions doesn't check response.status

### ISSUE THREAD

**Issue by ef4** [cardstack/cardstack#635]
If [this request](https://github.com/cardstack/cardstack/blob/3a4872e69cb5cd9c1a080ca8cb8dd5c61751c7fa/packages/data/addon/services/cardstack-data.js#L108) doesn't return a 200, we try to destructure an undefined value.

cc @balinterdi

**Comment by balinterdi** [comment]
Good catch, I'll tackle that next week.

**Comment by balinterdi** [comment]
@ef4 I submitted [the PR](https://github.com/cardstack/cardstack/pull/655) but I wonder if that doesn't add a guard that's never needed. I think a request to `/api/permissions/:path` can only do one of two things:

1) Return a 200 OK response with `may-update-resource` and `writable-fields` attributes in a JSON:API doc so the original, non-guarded code is correct.
2) Throw an error (with a status of 404) if the content-type doesn't exist, in which case control doesn't get to the next line – so the guard is unneeded.
