### ISSUE TITLE
speed up CI times by breaking down node, ember, and truffle tests into parallel jobs

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#637]
We should speed up our CI time by breaking down the node, ember, and truffle tests into parallel jobs.

**Comment by habdelra** [comment]
To clarify: right now we run all the node tests, and then all the ember tests, and finally all the truffle tests. I propose that we runt all the ember tests in one job, all the node tests in another job, and all the truffle tests in a 3rd job. (Not counting the node version matrix)

**Comment by ef4** [comment]
Yeah, that may help.

**Comment by ef4** [comment]
Also, the ember-tests section itself could get a big speed boost if we squash all the test suites together into a single `ember test` so the overhead of the build only happens once.

Also, I have come to suspect that Travis jobs are actually quite performant with multi-process workloads, and those have the benefit of sharing all the job startup costs (especially yarn). 

The test suite I'm happiest to work with lately is ember-auto-import's, and it runs 19 ember test suites in parallel in a single travis job, and finishes in 5 minutes.
