### ISSUE TITLE
Change README.md from Slack to Discord

### ISSUE THREAD

**Issue by afmsavage** [cardstack/cardstack#657]
The readme.md file for this repo still links and points users to join the Slack.  Not sure if this is still the route you want them to take, but would be nice not having to go through another Slack registration process only to find out it was for naught.

**Comment by habdelra** [comment]
thanks for catching this!

**Comment by habdelra** [comment]
fixed in https://github.com/cardstack/cardstack/commit/775b5a1557c1fa83c9ca8f7384ebc95b805c297a
