### ISSUE TITLE
Add support for setting the desired order of fields in the right edge

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#678]
Add support for setting the desired order of fields in the right edge. We can add a `sortPriority` field to the `fields` content type that works similarly to the `caption` field on this content type.

**Comment by balinterdi** [comment]
This seems to have been done in https://github.com/cardstack/cardstack/commit/3681ff232550b25889b2fa201a725a2d4fad95bd 

I wonder whether the fact that we now show fields in `cs-version-control` (`fieldsBelowFooter` and `fieldsAboveFooter`) plays nicely with `renderedFields` and `modelFields`, which are rendered by `cs-active-composition-panel`. I don't see what prevents a field in either `fieldsBelowFooter` or `fieldsAboveFooter` to be added again in `renderedFields` or `modelFields`.
