### ISSUE TITLE
Unable to use computed fields as part of field based grants

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#682]
In the scenario where you have a grant that uses a field dependent `who` relationship, and that field is a computed field, the grant will not be evaluated correctly, as the grant validation is not taking into account computed fields. 

From @ef4:

The root cause bug is that this code doesn’t go through Model#getField: https://github.com/cardstack/cardstack/blob/2d7f04ff1bdf4d9ccb150b96083006f32e147ebe/packages/hub/schema/grant.js#L277-L278

**Comment by habdelra** [comment]
@ef4 I'm looking more deeply at this, and I'm seeing that if we want to use the `Model` here, we need a `read()` to pass into the `Model`. If we create the Model in this function then that has some really significant ripples throughout the hub in that we need to obtain `read()` functions in all sorts of places where we don't need it currently (which totally looks possible--just dozens of method signature changes to accommodate this. would it be better to pass the `Model` around within the various schema classes instead of the `resource` object that we use now?

**Comment by ef4** [comment]
I think the thing we should create and pass around is a DocumentContext instance.
