### ISSUE TITLE
Unable to display relationship field in right edge editor when it doesn't appear in template

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#685]
There appears to be a bug where if you have a content type that has a relationship field, and that content type is being rendered in the editor, the relationship field will not appear in the right edge unless it is in the template. Currently we support displaying attribute fields int eh right edge that are not rendered in the template. We should extend this behavior to account for relationship fields as well.

**Comment by balinterdi** [comment]
Not sure where you had that problem but #727 fixes a case where fields in *owned relationships* with a name that matched a rendered field name didn't get rendered in the editor.

An example would be a `popularity` field of a blog post and a `popularity` field name in an owned (related) category.

The other case I can imagine is that the field that didn't appear in the editor was in a relationship that wasn't an owned one.
