### ISSUE TITLE
Use idiomatic Ember data to write files to S3

### ISSUE THREAD

**Issue by bagby** [cardstack/cardstack#686]
Currently, when we are using the `@cardstack/image` plugin, in the image upload modal we are saving the file by pointing to the Hub endpoint using `$.ajax` [here](https://github.com/cardstack/cardstack/blob/master/packages/image/addon/components/field-editors/image-upload-modal.js#L24):

```
  let jsonApiDocument = yield $.ajax({
      url: this.get('endpointUrl'),
      type: "POST",
      data,
      contentType: false,
      processData: false
  });

  this.get('store').pushPayload(jsonApiDocument);
  let { type, id } = jsonApiDocument.data;
  let fileRecord = this.get('store').peekRecord(type, id);

  return fileRecord;
```

We should be using more idiomatic ember-data:

```
  let cardstackFile = this.get('store').createRecord('cardstack-file', {...});
  yield cardstackFile.save();

  return cardstackFile;
```

This has several advantages, not the least of which is being able to control access to file uploads via grants, which we cannot currently because we are not sending the session withe the `$.ajax` request.

**Comment by habdelra** [comment]
fixed in https://github.com/cardstack/cardstack/pull/708
