### ISSUE TITLE
Constraint violations are not visible after failed save

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#688]
When you create a new document and encounter constraint violations in a collapsed section, we do not immediately display the violation. it is very confusing to the user why the content has not saved. it's actually quite difficult to get to the point where you see the constraint violation message. We need to fix this so it is immediately obvious to the user after you click the save button why the document has not saved.

![screen recording 2019-03-06 at 11 17 15 pm](https://user-images.githubusercontent.com/61075/53932234-a4f6f280-4066-11e9-900f-4ab9dd083cc8.gif)

**Comment by habdelra** [comment]
@balinterdi I wanted to bring this issue to your attention since I believe you originally worked on this. The user experience is less than ideal...

**Comment by balinterdi** [comment]
Yep, thanks, that's indeed a subpar UX. Is that the same when you *update* a resource (as opposed to creating a new one)? (I'd hope not as I think we even have tests that verify that the error message can be seen after hitting the Save/Update button.

**Comment by balinterdi** [comment]
@habdelra Done in #719 (including a test), could you review it?

The problem was that the action was passed to the wrong component so validation wasn't triggered by the click of the Save button, only on focusing out the editor fields.
