### ISSUE TITLE
Hiding a field from the editor still results in the field that has the editor overlay applied

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#697]
I have designated a field as hidden from the editor like so:
```js
    factory.addResource('computed-fields', 'author-name').withAttributes({
      editorOptions: { hideFromEditor: true },
      'computed-field-type': '@cardstack/core-types::alias',
      params: {
        'aliasPath': 'author.name',
      }
    }),
```

And in the component's template it is rendered as such:
```hbs
  <div>author: <span>{{content.authorName}}</span></div>
```

Yet it still receives an editor overlay even though it is hidden from the editor.
<img width="823" alt="Screen Shot 2019-03-08 at 9 15 58 PM" src="https://user-images.githubusercontent.com/61075/54064952-c9c6a380-41e7-11e9-9c57-deeb8628663a.png">

**Comment by balinterdi** [comment]
Fix implemented in #722
