### ISSUE TITLE
Add progress indicator to image upload modal

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#711]

**Comment by balinterdi** [comment]
@habdelra Do you mean we should show a progress indicator when the image is picked in the card picker (see my video here: https://cl.ly/1a95a3796673)? This is when a `POST /api/cardstack-files` and a `POST /api/cardstack-images` request is made.

If so, I believe this functionality should be added to the `card-picker` package (which is fine, I just want to see clearly in the matter – I first though this functionality is in the `image` package).

**Comment by habdelra** [comment]
yea, i wrote this issue before we had the overhauled card-picker. but yeah, the idea is that the images that we upload could be very large (and we want to encourage very large image uploads coupled with using image transformation services to downscale to a suitable resolution based on how the image is being used). Since large images can take longer to upload we should show the user some feedback on the upload progress for the image, so the system feels responsive. This would be a wonderful issue for you to pick up if you're interested.

**Comment by balinterdi** [comment]
I am!

**Comment by balinterdi** [comment]
Turns out the loading screen was already implemented so I just took some time to refactor some component and template code and fix an issue when loading an article that already had an image (an error was thrown in that case).

![](https://d2ddoduugvun08.cloudfront.net/items/0q1114173u210J241W0v/Image%202019-04-09%20at%2012.01.55%20PM.png?X-CloudApp-Visitor-Id=2833509)

See #737

**Comment by habdelra** [comment]
That’s not what I meant by loading—I meant the upload progress. So we can see a percentage of bytes uploaded as the upload completes.

**Comment by habdelra** [comment]
Heres some documentation https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent you’ll need to use the XHR api directly for this.

**Comment by balinterdi** [comment]
I'm simulating a slow network via Network throttling in Chrome DevTools (Fast 3G):

https://cl.ly/a3aee2c163fe

**Comment by habdelra** [comment]
nice!
