### ISSUE TITLE
Consider extracting the Git Hyperledger back out of `cardstack/git` and into its own package

### ISSUE THREAD

**Issue by mansona** [cardstack/cardstack#725]
Howdy folks 👋 

This is really just a continuation of a conversation that I started in https://github.com/cardstack/cardstack/pull/614 after it was merged. Essentially I wasn't 100% sure about the decision to merge the `git-hyperledger` package and the `git` package 🤔 

My reasoning is this: not everyone who is making a cardstack application will be using git-hyperledger but **everyone** who uses cardstack will be using a git datasource as part of the stack (either directly or internally as we have discussed over the last month or so). Therefore, it doesn't make sense to me that users that have not added git-hyperledger to their application (logically I mean) should be required to download the required depenedencies. Also it means that the git datasource now does two things that are not related instead of focusing on exactly one job (the unix philosophy).

My understanding of @alexspeller's arguments against having them as 2 separate packages is that it is harder to do, and that we needed to move fast and finish the integration. I would propose that we should make it easier for the git-hyperledger to do its work as an external package by potentially considering a plugin architecture for the git datasource that would provide things like `postCommit()` hooks that git-hyperledger could leverage (and any other bits that are required)

If you have any questions about this please let me know 👍

**Comment by alexspeller** [comment]
This represents my thoughts well. Essentially adding a hook architecture to the the git plugin is more complex to implement but is probably the "right" thing to do. Although if its _only_ used for this feature then it might be yak shaving. @mansona mentioned some other issues that it might solve with middlewares so that sounds useful for that too

**Comment by mansona** [comment]
Yes, for one of the custom cardstack projects we needed specific git functionality that wasn't yet available in the git datasource (or might not make sense to include upstream). In this case, it would have been really useful to have a plugin architecture to add this custom functionality that was specific to the project 👍 Instead we needed to "intercept" things that would have gone to the git datasource and do our work manually, which felt like the wrong level of abstraction at the time 🤔
