### ISSUE TITLE
Model-based encapsulation

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#733]
- no more global name space (i'm looking at you, fields!)
- data service is aware of which card is asking for information so that we know how to scope the response.
- the line between models and cards is blurry. Need to make a clearer distinction between what is a model and what is a card (generally today you are dealing with cards not models). make this more formal in the system.
- data service arguments to load a card are:
  - npm package (replaces type),
  - id,
  - version (aka branch). there are defaults. the right default depends on who is asking. 
  - data source (interchangeable with repo)

- relationships will need to be modified to use the tuple above. need to synthesize the type and id based on this tuple (figure out our rule for doing this).
- made a new type called cards?
  - the new type cards will use the new id format that includes this tuple

- making a developer oriented store for optimizing modifying the data for a card. think of thing that is more "card" oriented compared to how we are storing models in the git data source. 
- when serialized the card's package/id/version/repo can be derived from repo and file folder. (version is actually only realizable when exported from git).

- start with looking at where we are loading things by type and id. are we loading a "card" or a "model" (mostly its a card). let's make 2 new methods on searchers.get getModel() and getCard() and update all callers to use the more explicit API.

- When you want to get a model that needs to happen in the context of a card now (need to know whose asking).

- split version off of the API so that we are not fashioning relationships with the version bound into the ID. 

- when a document is saved we save a "snapshot"  of the document with the specific version in the index which is different than the "current" version (which is just an update of the current document's row). 
  - Need to also make sure that this process is both incremental and full--so that if the index is destroyed and the recreated we have all the snapshots. indexers can be amended to also emit history to support this full case (which might be a background step via jobs). 
  - Also we need the package version when saving the snapshot (in the meta). think about the developer use case, where a developer is constantly updating the package version--think about a feature where the version of the package is whatever the developer has checked out.
  - also, think about how we need to migrate card data between package versions.

- stop using static-models for defining card definitions (schema). schema is a new feature for cards. 
  - we care write it the same as we do for static-models, it's a new feature. 
  - probably very similar to how static models loads. this unlocks the ability to index data sources separately.

**Comment by balinterdi** [comment]
I very much welcome this issue as it addresses issues of clarification/simplification that I've bumped into several times.

For example, 
> the line between models and cards is blurry. Need to make a clearer distinction between what is a model and what is a card (generally today you are dealing with cards not models). make this more formal in the system.

was one of the first things I encountered and I'm happy to see it's covered, too.

@ef4 I also think it supersedes https://github.com/cardstack/cardstack/issues/579 as this seems to redesigns our schema system. Is that correct?

**Comment by habdelra** [comment]
I think #579 is definitely impacted, as the "fields" for a card different than the fields of a model.

**Comment by ef4** [comment]
#579 is related but I think it can be done somewhat independently of this work. We should keep it in mind though as we're doing this design.

The main thing #579 wants is making ember-data model generation happen just-in-time when you get a model. This is necessarily needed not just to keep non-readable fields out of the model, but also needed to support adding new cards dynamically.

**Comment by ef4** [comment]
@habdelra that's a good point, I think this issue can help clarify the handling of the right edge fields. Before, we didn't have a clear system for dealing with fields from "owned relationship" models. Some fields belonged to "the card", and some belonged to its owned models, and we needed to try to design about both scenarios.

Now there aren't any fields on the card itself, all fields belong to models inside the card, and that's the only scenario.
