### ISSUE TITLE
Research - upcoming changes to JSONAPI

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#784]
To-do:

- What changes are coming up? Share links to info and a couple copy-paste examples
- Are they breaking changes, new features, or both?
- Do we need to change our code at all? (will require conversation with other devs to figure this out)
- What is the timeline for JSONAPI to launch their changes?

**Comment by skarabocu** [comment]
1. https://docs.google.com/document/d/11nx-20E1mxiJAvOjFMpwa_DuBNZXyOUEMfM-2J-0kao/edit
2. Two main new features, profile parameter and query families.
3. The already existing code should work fine, but new features might help to organize the data better.
4. The official release date for JSON:API v1.1 is January 31st, 2019.

**Comment by ef4** [comment]
The bigger thing for us didn't make it into v1.1, but it's tentatively in v1.2. JSON:API operations.

**Comment by jenweber** [comment]
closed, no additional action needed
