### ISSUE TITLE
Add information on how to debug and step through hub/node code

### ISSUE THREAD

**Issue by courajs** [cardstack/cardstack#8]
I suspect interacting with `@cardstack/hub` will be many people's first time needing to step through the node portions of an ember-cli addon (myself included). It would be fantastic to include some information on how to do that, or link to a resource that walks through it.

**Comment by ef4** [comment]
The short answer is: use Visual Studio Code. It has the best Node debugger by far.

This repo has a .vscode configuration that is configured to launch the test suite or the server under the debugger.
