### ISSUE TITLE
CLI bug - updated pre-build app fails on deprecation app dep

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#811]
See https://github.com/babel/ember-cli-babel/pull/286

```
Could not find module `@ember/application/deprecations` imported from `(require)`
```

**Comment by jenweber** [comment]
Made a PR to the Octane blueprints here https://github.com/ember-cli/ember-octane-blueprint/pull/127, however since we depend on ember-cli-babel in other places, it seems I need to update those too.

**Comment by ef4** [comment]
It's not necessarily needed in all places. I think the important one for us is the one the app is using directly (the one you fixed above).

**Comment by jenweber** [comment]
Closed, fixed upstream
