### ISSUE TITLE
Proposal - Start a CHANGELOG

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#812]
I think we should start a CHANGELOG, given the growing team size and number of projects. For now, since this is pre-1.0, I think we should just track big features and breaking changes, but if people think certain bugfixes are important, they could be added. Usefulness > completeness. We could start with v0.13, and have just one top-level CHANGELOG for now.

Proposed format:

# Changelog

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/)

## [Unreleased]
- [FEATURE] something new described here #12456
- [BREAKING] very brief description and link to PR

### Added
- Version navigation.

### Changed
- Start using "changelog" over "change log" since it's the common usage.

### Removed
- Section about "changelog" vs "CHANGELOG".

**Comment by ef4** [comment]
I agree, let's do it.
