### ISSUE TITLE
CLI - implement cardstack play command

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#818]
`cardstack play`

- need to link the card in
- need to link card peer deps
- could use yarn aliasing to prevent collisions

**Comment by jenweber** [comment]
Notes:
Our entry points files need to be in a component so that that they are handled lazily by Embroider automatically.

**Comment by ef4** [comment]
> Didn't yet solve why Glimmer component were getting rewritten badly 

I think we did solve this: when linking the peerDeps, we need to find those deps relative to the embroider build output instead of relative to the app. That ensures we will use the V2-upgraded versions of the dependencies.
