### ISSUE TITLE
Bug - implicit "everyone" readers don't work

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#826]
In Cardboard, resources marked readable by everyone were not available. The failing test is in Cardboard, called "allows anonymous to view published article"

**Possible solutions:**

~~Edit bootstrap schema to create an "everyone" group. Try yarn linking the latest version of the hub and see if grant tests pass in Cardboard. This might cause problems in other areas though, but failed tests should give more info.~~

We may possibly need some custom handling in the cardstack hub for everyone groups.
In `searchers` we could make a groups searcher that follows the same pattern as `permissions.js`

Should note that the point is to avoid an unnecessary db hit to see that "everyone" exists.

**Comment by jenweber** [comment]
Adding to `bootstrap-schema` (just to see if it fixes it) fails with 

> Error: group must have a search-query attribute


```js
// bootstrap schema, added at line 807
  {
    type: 'groups',
    id: '@cardstack/hub'
  },
  {
    type: 'groups',
    id: 'everyone'
  },
```

I had to do some linking shenanigans outlined in #828

**Comment by jenweber** [comment]
I made a new searcher to handle everyone grants (and called it `everyone-grants`), but I'm not sure how/where it should be called. Is there somewhere in bootstrap-schema that should indicate when to use this searcher?'

```
  {
    type: 'data-sources',
    id: 'permissions',
    attributes: {
      'source-type': '@cardstack/hub::permissions',
    }
  },
  {
    type: 'data-sources',
    id: '???????????',
    attributes: {
      'source-type': '@cardstack/hub::everyone-grants',
    }
  },
```

**Comment by ef4** [comment]
Yes, that snippet would work and the id doesn't matter.

**Comment by jenweber** [comment]
I am falling back to adding some handling into the validation for groups.

Here's what I tried:

```js
// added to bootstrap-schema. Without this, the searcher is never hit
  {
    type: 'data-sources',
    id: 'permissions',
    attributes: {
      'source-type': '@cardstack/hub::everyone-grants',
    }
  },
```

I defined a searcher called `everyone-grants.js` with a get method:

```
  async get(session, type, id, next) {
    if (type === 'groups' && id === 'everyone') {
      return {
        data: {
           id: 'everyone',
           type: 'groups',
           attributes: {
             'search-query': {}
           }
        }
      };
    } else {
      return next();
    }
  }
```

`search-query: {}` is needed to overcome this error:

```text
 Error: group must have a search-query attribute: {
  "id": "everyone",
  "type": "groups",
  "meta": {
    "source": "everyone-grants"
  }
}
```

But that uncovers:
```
Error: group everyone search-query is required to filter by exact types: {}
```

If I skip that check in the hub codebase, the test still fails with 

```
Error: No such resource local-hub/articles/<someuuid>
```

**Comment by jenweber** [comment]
I debugged some more and discovered that if I bypassed the group validations, it was ok, so I'm moving forward with that. It needs some refactoring but the working code is on the branch `bugfix-826`. It passes tests for Cardboard. I need to check the rest of the Cardstack mono repo tests.
