### ISSUE TITLE
The Right Edge dropdown UI for has-many should reflect search constraints

### ISSUE THREAD

**Issue by jenweber** [cardstack/cardstack#848]
When you search for a record to associate, the search follows some unexpected rules, so we should make those rules discoverable in the UI. Imagine you have a photo called "My photo."

- Searching "My" has no results
- Searching "My pho" has no results
- Searching "photo" returns results

There is a character minimum plus a whole-word search in place.

Although we could relax the settings or make them configurable, I think they are sensible defaults for frontend-to-backend communication. I think the real solution here is that the UI should somehow indicate the constraints.

**Comment by habdelra** [comment]
we are using postgres' full text searcher for our full text search--it's `plainto_tsquer`y the docs are here:  https://www.postgresql.org/docs/9.6/functions-textsearch.html
the idea is that postgres will use english semantics to create word stems from the string fields that it indexes
as part of that it throws out common english words
I think "my" is probably one of those words
for instance: plainto_tsquery('english', 'The Fat Rats') creates these word stems: 'fat' & 'rat'
You can actaully see this in the documents DB's q column.

also this type of search requires queries against complete words. for searches that are substrings (like "pho" matching the indexed word "photo" you need to use `prefix`, like we do here in the tests (which works better for searching against proper nouns): https://github.com/cardstack/cardstack/blob/master/packages/pgsearch/node-tests/searcher-test.js#L813

**Comment by habdelra** [comment]
You can use this SQL to see what the index looks like: 
```sql
select plainto_tsquery('english', 'My photo.')
```

Actually returns:
```
'photo'
```

Meaning that "My" is actually thrown out because it is too common of an english word (these rules should be configurable in postgres if you dont agree with them)

**Comment by habdelra** [comment]
also consider the use of an or clause to use both types of searching:
```
{
  filter:
    or: [
      { title: 'My pho' },
      { title: { prefix: 'My pho' } }
    ]
}
```

**Comment by jenweber** [comment]
Closed, obsolete with new-hub
