### ISSUE TITLE
Fields can easily pickup grants not intended for them

### ISSUE THREAD

**Issue by habdelra** [cardstack/cardstack#856]
Right now the way fields discover grants that apply to them to to check for grants that mention the field's id in the grants' `fields` relationship (which is expected), or fields associate themselves with grants that have no `fields` relationship. https://github.com/cardstack/cardstack/blob/master/packages/hub/schema/field.js#L54

Having fields associating themselves with grants that have no `fields` relationship is problematic. I believe this was originally meant as a shorthand, so that it would be easy to create grants written from the content-type perspective that could bestow field level permissions against all the fields in the content-type without having to be pedantic in the grant definition (which would be difficult to manage if fields are added or removed from a content-type). 

However, what we are seeing is that it is too easy for these types of grants (grants targetted towards all the fields of a content type by not specifying a `fields` relationship) to inadvertently "leak" out of the content type and apply to all fields in the entire system (across all content-types). If a grant author needs to have field specific grants, what that actually means is that the grant author will need to create field level grants for _all_ fields in the system. The grant authoring short hand that is used to target all the fields of a content-type can ***not*** be used as soon as field specific grant in any single content type is required. This is a troll that has pretty severe consequences (as it will leak fields' values or field write capabilities that were intended to be locked down when it surfaces).

I would suggest that in the `Field` class that we pass into the field all the content-type schema models as well so that instead of fields just associating themselves with any grant that doesn't have a `fields` relationship, we can instead look up the content-type's `fields` property on the `types` relationship of the grant (when it has no `fields`) and then use that as a means to see if the grant applies to the field or not--so effectively the field will know which content-types it is a part of and only pickup the grants using the special content-type short-hand when the field belongs to that content-type.

**Comment by habdelra** [comment]
This was an issue that we worked around in https://github.com/cardstack/project-template/commit/48ff2382f9e0b1cd5930e093e2b4fb4ee8099c15

**Comment by ef4** [comment]
This is entangled with the fact that fields are not per-content-type right now, but they are under the new design you're working on.
