### ISSUE TITLE
Contents of Right Edge should change when changing focus between card and UI control on a card

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#931]
Right edge properties panel displays properties only for the currently selected object, be it entire card or selected component. 
Focus change can be triggered explicitly by clicking on a component, or on a card itself outside of boundaries of any component. 
When adding a new component to the card, it automatically becomes selected, and its properties are loaded into the right edge. 

See attached motion study for transition animation: https://drive.google.com/open?id=1Q76u-dp20Vk9z7qpdNjJq4xJkjj_wlyn

**Comment by bagby** [comment]
@dnaidionov I believe this issue was finished by #987 (which closed #975). The animations are still not completed (which is probably true of most stories so far), perhaps we should have a separate animation story for this?

**Comment by dnaidionov** [comment]
I created a separate story around highlighting (#993) and another about animating transitions (#992)
