### ISSUE TITLE
animate drag & drop to rearrange fields in card schema

### ISSUE THREAD

**Issue by dnaidionov** [cardstack/cardstack#934]
Should use ember-animated.

A shortcut if we can't use animated would be https://github.com/SortableJS/ember-sortablejs

**Comment by bagby** [comment]
Some work has been done on this in the [ui-components-text-field](https://github.com/cardstack/cardstack/tree/ui-components-text-field) branch

**Comment by dnaidionov** [comment]
To complete this requires ember-animated, and currently, there are some bugs there blocking this work.
