### ISSUE TITLE
Contents shouldn't move when card-renderer or field-renderer is highlighted

### ISSUE THREAD

**Issue by burieberry** [cardstack/cardstack#965]
Card renderer:
- Icon budges from highlighted state to unhighlighted
<img width="603" alt="card-renderer" src="https://user-images.githubusercontent.com/16160806/68491203-65496180-0218-11ea-9149-84a58121db69.png">

Field renderer:
- Text budges from highlighted state to unhighlighted
- Something off with borders
<img width="585" alt="field-renderer" src="https://user-images.githubusercontent.com/16160806/68491204-65496180-0218-11ea-8351-74ead40486aa.png">

**Comment by dnaidionov** [comment]
I think the issue is that we are only displaying the border when the card is selected, and that changes the inner dimensions of the box. Maybe the border should always be there, but transparent or same color as card background. And selecting the component only changes the border color.
